#!/usr/bin/env python3
"""Bake the hand-drawn POI category icons into src/components/icons/poi_icons.h.

    python3 scripts/gen_poi_icons.py

Source: src/components/icons/poi_icons_24.png, a 240x24 sprite sheet, ten 24x24
1bpp glyphs side by side in MapSafetyCategory order (MapPointTypes.h:19-31):
water, shelter, hut, lodging, fuel, hospital, pharmacy, rescue,
emergency_phone, transport.

Why a PNG source rather than SVG, unlike gen_pin_icons.py / gen_home_icons.py:
these are authored as pixel art at the exact 24x24 target size (the
maintainer's own cartographic-convention argument, 2026-08-24 -- a mark this
small is drawn for its size, not scaled down from a bigger design), so there
is no vector to rasterize. Edit the PNG directly, pixel by pixel, and rerun
this script.

Emits `freeink::Icon` structs in the same format
freeink-sdk/libs/assets/Icons/tools/gen_icons.py emits (1bpp, MSB first, bit 1
= leave the pixel alone, bit 0 = ink, opticalCenterY = content's centre of
mass row), so GfxRenderer::drawMono1bpp() draws these the same way it draws
search24.h.

NOT WIRED IN YET. MapPointMarks.cpp still draws every category from
IMapCanvas primitives -- that was a deliberate 2026-08-21 decision
(MapPointMarks.h:18-46) made against Lucide at 9px, not against a bitmap
designed for 24px. Swapping the switch in MapPointMarks.cpp to draw these
instead is a separate step, once the categories flagged in review (lodging,
rescue) are settled.

Needs Pillow only -- no rasterizer, since the source is already a raster.
"""
import os
import re
import shutil
import subprocess
import sys

from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPRITE = os.path.join(REPO, "src/components/icons/poi_icons_24.png")
OUT = os.path.join(REPO, "src/components/icons/poi_icons.h")

GLYPH_PX = 24
THRESHOLD = 110

# Sprite order, left to right -- must match MapSafetyCategory
# (MapPointTypes.h:19-31), which is the point file's own wire id order.
CATEGORIES = ["water", "shelter", "hut", "lodging", "fuel",
              "hospital", "pharmacy", "rescue", "emergency_phone", "transport"]


def pack(img):
    """-> (bytes, opticalCenterY). 1 = transparent, 0 = ink, MSB first."""
    width, height = img.size
    pixels = img.load()
    data = []
    sum_y = 0
    count = 0
    for y in range(height):
        for x_byte in range(0, width, 8):
            byte = 0
            for bit in range(8):
                x = x_byte + bit
                white = 1
                if x < width and pixels[x, y] < THRESHOLD:
                    white = 0
                    sum_y += y
                    count += 1
                byte |= white << (7 - bit)
            data.append(byte)
    return data, (round(sum_y / count) if count else height // 2)


def ident(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def pascal(name):
    return "".join(part.capitalize() for part in name.split("_"))


def emit(alias, img):
    data, centre = pack(img)
    width, height = img.size
    bits = f"icon_poi_{ident(alias)}_bits"
    body = ", ".join(f"0x{b:02X}" for b in data)
    return [
        f"// {alias}",
        f"static const uint8_t {bits}[] = {{{body}}};",
        f"static const freeink::Icon icon_poi_{ident(alias)} = "
        f"{{{width}, {height}, {centre}, {bits}}};",
        "",
    ]


def main():
    if not os.path.exists(SPRITE):
        sys.exit(f"ERROR: missing sprite sheet: {SPRITE}")
    sheet = Image.open(SPRITE).convert("L")
    if sheet.size != (GLYPH_PX * len(CATEGORIES), GLYPH_PX):
        sys.exit(
            f"ERROR: expected a {GLYPH_PX * len(CATEGORIES)}x{GLYPH_PX} sprite "
            f"sheet ({len(CATEGORIES)} x {GLYPH_PX}px glyphs), got {sheet.size}"
        )

    out = [
        "#pragma once",
        "",
        '#include "Icon.h"',
        "",
        "#include <cstdint>",
        "",
        "// Generated by scripts/gen_poi_icons.py from",
        "// src/components/icons/poi_icons_24.png. Do not edit.",
        f"// {GLYPH_PX}px POI category glyphs, drawn with GfxRenderer::drawMono1bpp().",
        "// NOT wired into MapPointMarks.cpp yet -- see the script's own docstring.",
        "",
    ]

    for i, cat in enumerate(CATEGORIES):
        crop = sheet.crop((i * GLYPH_PX, 0, (i + 1) * GLYPH_PX, GLYPH_PX))
        out += emit(cat, crop)

    out.append("static const freeink::Icon* const kPoiIconByCategory[] = {")
    out.append("    nullptr,  // MapSafetyCategory::Unknown = 0, no glyph")
    for cat in CATEGORIES:
        out.append(f"    &icon_poi_{ident(cat)},  // {pascal(cat)}")
    out.append("};")
    out.append("")

    with open(OUT, "w") as handle:
        handle.write("\n".join(out))
    if shutil.which("clang-format"):
        subprocess.run(["clang-format", "-i", OUT], check=True)
    else:
        print("warning: clang-format not found -- run it on the output before committing")
    print(f"wrote {OUT}: {len(CATEGORIES)} icons")


if __name__ == "__main__":
    main()
