#!/usr/bin/env python3
"""Bake the Home screen's row icons into src/components/icons/home_icons.h.

    python3 scripts/gen_home_icons.py

Emits `freeink::Icon` structs in exactly the format
freeink-sdk/libs/assets/Icons/tools/gen_icons.py emits (1bpp, MSB first, bit 1 =
leave the pixel alone, bit 0 = ink, opticalCenterY = the content's centre of
mass row), so `GfxRenderer::drawMono1bpp()` draws these the same way it draws
`search24.h`.

Two reasons this exists next to the SDK generator rather than calling it:

  * it needs **rsvg-convert**, which is not on every machine here; this one
    falls back to cairosvg, the same way scripts/gen_pin_icons.py does.
  * the Explore icon is the **ExplorInk mark**, not a Lucide glyph, and it is
    not square. The SDK generator is square-only (`--sizes` feeds both w and h).

Sizes are the Home row's, not a knob: 32 px for the row glyphs, 22 px for the
chevron. Both are device pixels on the 480 px wide panel.
"""
import io
import os
import re
import shutil
import subprocess
import sys

from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUCIDE = os.path.join(REPO, "freeink-sdk/libs/assets/Icons/lucide/icons")
LOGO = os.path.join(REPO, "src/images/logo.svg")
OUT = os.path.join(REPO, "src/components/icons/home_icons.h")

# Same threshold the SDK generator uses, so a glyph baked here and one baked
# there weigh the same on the panel.
THRESHOLD = 110
ROW_SIZE = 32
CHEVRON_SIZE = 22

# alias -> lucide name. Explore is handled separately (the brand mark).
LUCIDE_ICONS = [
    ("trips", "backpack", ROW_SIZE),
    ("pins", "map-pin", ROW_SIZE),
    ("wallet", "wallet", ROW_SIZE),
    ("sync", "refresh-cw", ROW_SIZE),
    ("transfer", "wifi", ROW_SIZE),
    ("settings", "settings", ROW_SIZE),
    ("chevron", "chevron-right", CHEVRON_SIZE),
]


def rasterise(svg_path, width, height):
    if shutil.which("rsvg-convert"):
        png = subprocess.run(
            ["rsvg-convert", "-w", str(width), "-h", str(height), svg_path],
            capture_output=True,
            check=True,
        ).stdout
    else:
        import cairosvg

        png = cairosvg.svg2png(url=svg_path, output_width=width, output_height=height)
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    flat = Image.new("RGBA", img.size, (255, 255, 255, 255))
    flat.paste(img, mask=img.split()[3])
    return flat.convert("L")


def pack(img):
    """-> (bytes, opticalCenterY). 1 = transparent, 0 = ink, MSB first."""
    width, height = img.size
    pixels = img.load()
    data = []
    sum_y = 0
    count = 0
    for y in range(height):
        for x_byte in range(0, width, 8):
            byte = 0
            for bit in range(8):
                x = x_byte + bit
                white = 1
                if x < width and pixels[x, y] < THRESHOLD:
                    white = 0
                    sum_y += y
                    count += 1
                byte |= white << (7 - bit)
            data.append(byte)
    return data, (round(sum_y / count) if count else height // 2)


def ident(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def emit(alias, img, note):
    data, centre = pack(img)
    width, height = img.size
    bits = f"icon_{ident(alias)}_bits"
    body = ", ".join(f"0x{b:02X}" for b in data)
    return [
        f"// {note}",
        f"static const uint8_t {bits}[] = {{{body}}};",
        f"static const freeink::Icon icon_{ident(alias)} = "
        f"{{{width}, {height}, {centre}, {bits}}};",
        "",
    ]


def main():
    out = [
        "#pragma once",
        "",
        "#include <Icon.h>",
        "",
        "#include <cstdint>",
        "",
        "// Generated by scripts/gen_home_icons.py. Do not edit.",
        f"// Row glyphs {ROW_SIZE}px, chevron {CHEVRON_SIZE}px, drawn with"
        " GfxRenderer::drawMono1bpp().",
        "",
        "// These ARE the Lucide icons the icon rule asks for (the parent repo's",
        "// CLAUDE.md, \"Icons: prefer Lucide\"): every glyph below names its Lucide",
        "// source SVG, taken from freeink-sdk/libs/assets/Icons/lucide/icons/. Nothing",
        "// here is hand-drawn, and Home no longer uses the older hand-rolled bitmaps",
        "// (icons/wifi.h, settings2.h, transfer.h, bookmark.h -- still used by other",
        "// screens through the UIIcon table; the parent repo's",
        "// docs/icon-migration-plan.md tracks those). The Home screen's own doc is",
        "// ../../../docs/home-screen.md.",
        "//",
        "// Two deliberate deviations, so the next reader does not have to re-litigate",
        "// them:",
        "//",
        "//   * `explore` is the **ExplorInk brand mark** (src/images/logo.svg), not a",
        "//     Lucide glyph. The maintainer asked for the mark on that row",
        "//     (2026-08-21). A brand mark has no Lucide equivalent, so the rule does",
        "//     not reach it.",
        "//   * the **rasteriser** is scripts/gen_home_icons.py, not the SDK's own",
        "//     libs/assets/Icons/tools/gen_icons.py. Same output format (freeink::Icon,",
        "//     1bpp MSB-first, bit 0 = ink, opticalCenterY), same threshold 110. The",
        "//     SDK script needs rsvg-convert, which is not installed on the build",
        "//     machine, and it is square-only -- the brand mark is 32x31. Our script",
        "//     falls back to cairosvg, exactly as scripts/gen_pin_icons.py already",
        "//     does. Install librsvg2-bin and the two paths agree.",
        "",
    ]

    # Explore: the ExplorInk mark, scaled to the row glyph's height.
    logo = rasterise(LOGO, ROW_SIZE, ROW_SIZE)
    logo_ink = logo.point(lambda v: 0 if v < THRESHOLD else 255, "L")
    box = logo_ink.point(lambda v: 255 if v < THRESHOLD else 0, "L").getbbox()
    if box:
        logo_ink = logo_ink.crop(box)
        # pad width to a byte boundary so the stride stays honest at the blit
        pad_w = (logo_ink.size[0] + 7) // 8 * 8
        padded = Image.new("L", (pad_w, logo_ink.size[1]), 255)
        padded.paste(logo_ink, ((pad_w - logo_ink.size[0]) // 2, 0))
        logo_ink = padded
    out += emit("explore", logo_ink, "explore: the ExplorInk mark (src/images/logo.svg)")

    for alias, lucide, size in LUCIDE_ICONS:
        svg = os.path.join(LUCIDE, lucide + ".svg")
        if not os.path.exists(svg):
            sys.exit(f"missing svg for '{alias}': {svg}")
        out += emit(alias, rasterise(svg, size, size), f"{alias}  (lucide: {lucide})")

    with open(OUT, "w") as handle:
        handle.write("\n".join(out))
    # clang-format owns the byte arrays' line breaks. Without this the script
    # emits one very long line per icon, CI's format check fails it, and the next
    # regeneration shows up as churn against the formatted file in git.
    if shutil.which("clang-format"):
        subprocess.run(["clang-format", "-i", OUT], check=True)
    else:
        print("warning: clang-format not found -- run it on the output before committing")
    print(f"wrote {OUT}: {len(LUCIDE_ICONS) + 1} icons")


if __name__ == "__main__":
    main()
