#!/usr/bin/env python3
"""
Generate the compiled ride/hike/cycle mode masks from data/mapstyle.json's
`modes` block.

MapModeMaskDefaults.h is a build product, like lib/I18n/I18nKeys.h -- gitignored,
regenerated on every build (wired as a pre: step in platformio.ini next to
gen_i18n.py and build_html.py). data/mapstyle.json is the source: it already
lives in this repo and is the device's definitive style, so the firmware
builds standalone with nothing read from outside it.

The style is authored in the separate laptop-side tooling repo (its webapp
writes this data/mapstyle.json directly) -- that direction crosses repos on
purpose, but nothing here reads back across that boundary. See
docs/mapstyle.json.md.

Usage:
    python3 scripts/gen_mode_masks.py [style_path [output_path]]

Defaults: data/mapstyle.json -> src/activities/map/MapModeMaskDefaults.h.
"""
import json
import os
import sys

# Fixed order, independent of the JSON's key order -- this is what
# MapRideMode (Ride=0, Hike=1, Cycle=2) and MapModeMasks's default array
# assume.
_MODE_ORDER = ["ride", "hike", "cycle"]

# The tile format's own class_id enum (mapbuilder/tilegen/class_spec.py, mirrored in
# MapClassEnum.h). Owned by the tile format, not by the style -- duplicated
# here rather than imported because nothing outside this repo may be read to
# build this repo, and this list is a one-way door the same way the tile
# format's is (docs/map-data-spec.md, "The class enum").
_CLASS_ID = {
    "unknown": 0,
    "motorway": 1,
    "trunk": 2,
    "primary": 3,
    "secondary": 4,
    "tertiary": 5,
    "unclassified": 6,
    "residential": 7,
    "living_street": 8,
    "service": 9,
    "pedestrian": 10,
    "track": 11,
    "bridleway": 12,
    "cycleway": 13,
    "footway": 14,
    "path": 15,
    "steps": 16,
    "construction": 17,
    "ferry": 18,
    "railway": 19,
    "aerialway": 20,
}

_HEADER_NOTE = "Generated by scripts/gen_mode_masks.py from data/mapstyle.json. Do not hand-edit."


def compute_masks(style):
    """Returns {mode_name: mask}, or exits the build on any bad input.

    Fatal, not warn-and-continue: this is a generated file, and a mistake
    that only warns is a mistake that ships. An unknown class name or an
    empty mask are both build errors, never a 0x00000000 that draws nothing
    and looks like a broken card (docs/map-data-spec.md, "Mode is a
    render-time filter").
    """
    modes = style.get("modes", {})
    masks = {}
    for mode_name in _MODE_ORDER:
        classes = modes.get(mode_name, {}).get("classes", [])
        mask = 0
        for name in classes:
            if name not in _CLASS_ID:
                sys.exit(f"gen_mode_masks.py: mode '{mode_name}': unknown class '{name}'")
            mask |= 1 << _CLASS_ID[name]
        if mask == 0:
            sys.exit(f"gen_mode_masks.py: mode '{mode_name}' resolves to an empty class mask "
                      f"-- a mode that draws no roads is never what a style file means")
        masks[mode_name] = mask
    return masks


def gen_cpp(masks):
    lines = [
        "#pragma once",
        "",
        f"// {_HEADER_NOTE}",
        "",
        "#include <cstdint>",
        "",
    ]
    for mode_name in _MODE_ORDER:
        cpp_name = "".join(p.capitalize() for p in mode_name.split("_"))
        lines.append(f"inline constexpr uint32_t kDefault{cpp_name}Mask = 0x{masks[mode_name]:08x}u;")
    lines.append("")
    return "\n".join(lines)


def main(repo_root, style_path=None, output_path=None):
    if style_path is None:
        style_path = os.path.join(repo_root, "data", "mapstyle.json")
    if output_path is None:
        output_path = os.path.join(repo_root, "src", "activities", "map", "MapModeMaskDefaults.h")

    if not os.path.isfile(style_path):
        sys.exit(f"gen_mode_masks.py: {style_path} not found")

    with open(style_path) as f:
        style = json.load(f)

    masks = compute_masks(style)
    for mode_name in _MODE_ORDER:
        print(f"gen_mode_masks.py: {mode_name} 0x{masks[mode_name]:08x}")

    with open(output_path, "w") as f:
        f.write(gen_cpp(masks))
    print(f"gen_mode_masks.py: wrote {output_path}")


# PlatformIO/SCons entry point -- Import and env are SCons builtins injected at
# runtime. `__file__` is not defined in that exec environment (the same trap
# git_branch.py avoids the same way), so the repo root has to come from env
# rather than from this file's own path.
if __name__ == "__main__":
    _repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(_repo_root, *sys.argv[1:3])
else:
    try:
        Import("env")  # noqa: F821
        main(env["PROJECT_DIR"])  # noqa: F821
    except NameError:
        pass
