#!/usr/bin/env python3
"""
Generate the compiled MapStyle instance from data/mapstyle.json.

MapStyleDefaults.h is a build product, like MapModeMaskDefaults.h and
lib/I18n/I18nKeys.h -- gitignored, regenerated on every build (wired as a
pre: step in platformio.ini, and as a CMake custom command for the host
build in test/CMakeLists.txt). data/mapstyle.json is the source: it lives in
this repo and is the device's definitive style, so the firmware builds
standalone with nothing read from outside it.

Because the host build regenerates from the same file, editing the style in
mapbuilder's webapp and rebuilding test/map_preview shows the change without
flashing anything. See docs/mapstyle.json.md.

Usage:
    python3 scripts/gen_mapstyle.py [style_path [output_path]]

Defaults: data/mapstyle.json -> src/activities/map/MapStyleDefaults.h.
"""
import json
import os
import sys

# The tile format's own class_id enum (mapbuilder/class_spec.py, mirrored in
# MapClassEnum.h). Duplicated here for the same reason gen_mode_masks.py
# duplicates it: nothing outside this repo may be read to build this repo.
_CLASS_ID = {
    "unknown": 0,
    "motorway": 1,
    "trunk": 2,
    "primary": 3,
    "secondary": 4,
    "tertiary": 5,
    "unclassified": 6,
    "residential": 7,
    "living_street": 8,
    "service": 9,
    "pedestrian": 10,
    "track": 11,
    "bridleway": 12,
    "cycleway": 13,
    "footway": 14,
    "path": 15,
    "steps": 16,
    "construction": 17,
    "ferry": 18,
    "railway": 19,
    "aerialway": 20,
}

# MapClassEnum.h's kClassEnumSlots -- the array length MapStyle declares.
_CLASS_SLOTS = 32

_HEADER_NOTE = "Generated by scripts/gen_mapstyle.py from data/mapstyle.json. Do not hand-edit."


def _round_px(value, what):
    """Style lengths are floats; the canvas takes int pixels. Round half up.

    Python's round() is banker's rounding, which would turn a 2.5px casing
    into 2 and a 3.5px one into 4 -- not what a style author reading the
    file would predict.
    """
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        sys.exit(f"gen_mapstyle.py: {what}: expected a number, got {value!r}")
    if value < 0:
        sys.exit(f"gen_mapstyle.py: {what}: negative length {value}")
    return int(value + 0.5)


def road_widths(style):
    """Returns (widths, casings), each kClassEnumSlots long, indexed by class_id.

    A class with no rule of its own gets layers.roads.default's width, which
    is what the laptop-side renderer does (mapbuilder/style.py resolve_rule).
    A hidden class, and every reserved enum slot, gets width 0 -- MapRenderer
    skips those without drawing.
    """
    roads = style.get("layers", {}).get("roads")
    if roads is None:
        sys.exit("gen_mapstyle.py: layers.roads missing")

    widths = [0] * _CLASS_SLOTS
    casings = [0] * _CLASS_SLOTS
    if not roads.get("enabled", True):
        print("gen_mapstyle.py: layers.roads.enabled is false -- no roads will be drawn")
        return widths, casings

    default_width = _round_px(roads.get("default", {}).get("width", 1), "layers.roads.default.width")
    for class_id in _CLASS_ID.values():
        widths[class_id] = max(default_width, 1)

    for index, rule in enumerate(roads.get("rules", [])):
        classes = rule.get("match", {}).get("class", [])
        for name in classes:
            if name not in _CLASS_ID:
                sys.exit(f"gen_mapstyle.py: layers.roads.rules[{index}]: unknown class '{name}'")
            if rule.get("hidden", False):
                widths[_CLASS_ID[name]] = 0
                casings[_CLASS_ID[name]] = 0
                continue
            width = _round_px(rule.get("width", default_width), f"layers.roads.rules[{index}].width")
            # A visible class must stay visible. Rounding 0.4px to 0 would
            # silently delete a road class that the style file draws.
            width = max(width, 1)
            if width > 255:
                sys.exit(f"gen_mapstyle.py: class '{name}' width {width}px does not fit a uint8_t")
            widths[_CLASS_ID[name]] = width

            casing = _round_px(rule.get("casing_px", 0), f"layers.roads.rules[{index}].casing_px")
            # Two casings plus at least one white pixel between them, or there
            # is no white left and the "casing" is just a solid black line
            # drawn the slow way, in two passes.
            if casing > 0 and 2 * casing >= width:
                casing = 0
                print(f"gen_mapstyle.py: class '{name}': casing_px leaves no white inside a {width}px "
                      f"road -- drawing it solid instead")
            casings[_CLASS_ID[name]] = casing

    if not any(widths):
        sys.exit("gen_mapstyle.py: every road class resolves to width 0 -- a style that draws no "
                 "roads at all is never what a style file means")
    return widths, casings


def puck(style):
    """(radius, ring, arrow) for layers.position, in px.

    Disabled means radius 0, which MapRenderer reads as "no disc, arrow only".
    The arrow is kept either way: a position that draws nothing is never what
    a style file means.
    """
    position = style.get("layers", {}).get("position", {})
    arrow = _round_px(position.get("arrow_px", 28), "layers.position.arrow_px")
    if not position.get("enabled", True):
        print("gen_mapstyle.py: layers.position.enabled is false -- arrow only, no puck disc")
        return 0, 0, arrow
    radius = _round_px(position.get("puck_radius_px", 0), "layers.position.puck_radius_px")
    ring = _round_px(position.get("ring_px", 0), "layers.position.ring_px")
    if radius and ring >= radius:
        sys.exit(f"gen_mapstyle.py: layers.position.ring_px {ring} leaves no white disc inside "
                 f"puck_radius_px {radius}")
    for name, value in (("puck_radius_px", radius), ("ring_px", ring), ("arrow_px", arrow)):
        if value > 255:
            sys.exit(f"gen_mapstyle.py: layers.position.{name} {value}px does not fit a uint8_t")
    return radius, ring, arrow


# mapstyle.json's hatch strings are matplotlib's. Only the character matters
# here; the repeat count ("XXXX") is a matplotlib density knob, and density on
# the device comes from hatch_spacing_px, in device pixels like every other
# length. Maps to MapAreaFill::Pattern.
_HATCH_PATTERN = {
    "/": "Diagonal",
    "\\": "AntiDiagonal",
    "-": "Horizontal",
    "|": "Vertical",
    "X": "Cross",
    "x": "Cross",
    "+": "Cross",
}


def _hatch(rule, what):
    """(pattern enum name, spacing px) for a layer rule's fill.

    A rule with no `fill: hatch` draws no fill at all -- outline only, or
    nothing if the outline is 0 too. That is a legitimate style, so it is not
    an error.
    """
    if rule.get("fill") != "hatch":
        return "None", 0
    text = str(rule.get("hatch", "")).strip()
    if not text:
        sys.exit(f"gen_mapstyle.py: {what}: fill is hatch but no hatch pattern given")
    pattern = _HATCH_PATTERN.get(text[0])
    if pattern is None:
        sys.exit(f"gen_mapstyle.py: {what}: hatch '{text}' starts with a character this renderer "
                 f"has no pattern for (use one of {''.join(sorted(_HATCH_PATTERN))})")
    spacing = _round_px(rule.get("hatch_spacing_px", 0), f"{what}.hatch_spacing_px")
    if spacing <= 0:
        sys.exit(f"gen_mapstyle.py: {what}: hatch needs a hatch_spacing_px above 0 "
                 f"-- spacing 0 would be a solid fill, which 1-bit cannot afford")
    if spacing > 255:
        sys.exit(f"gen_mapstyle.py: {what}: hatch_spacing_px {spacing} does not fit a uint8_t")
    return pattern, spacing


def buildings(style):
    """(enabled, outline px, hatch pattern, hatch spacing)."""
    layer = style.get("layers", {}).get("buildings", {})
    if not layer.get("enabled", False):
        return False, 0, "None", 0
    rule = layer.get("rule", {})
    outline = _round_px(rule.get("outline_width", 0), "layers.buildings.rule.outline_width")
    pattern, spacing = _hatch(rule, "layers.buildings.rule")
    if outline == 0 and pattern == "None":
        sys.exit("gen_mapstyle.py: layers.buildings is enabled but draws neither an outline nor a hatch "
                 "-- that reads every building off the card to draw nothing. Disable the layer instead.")
    return True, outline, pattern, spacing


def water(style):
    """(enabled, line px, hatch pattern, hatch spacing).

    One line width for every waterway: the tile format gives water no class, so
    the river/stream/canal rules cannot be told apart on the device and the
    layer default is what applies. The area hatch is taken from whichever rule
    carries a `fill`, since only areas have one.
    """
    layer = style.get("layers", {}).get("water", {})
    if not layer.get("enabled", False):
        return False, 0, "None", 0
    line = max(_round_px(layer.get("default", {}).get("width", 1), "layers.water.default.width"), 1)
    if line > 255:
        sys.exit(f"gen_mapstyle.py: water line width {line}px does not fit a uint8_t")
    pattern, spacing = "None", 0
    for index, rule in enumerate(layer.get("rules", [])):
        if rule.get("fill") == "hatch":
            pattern, spacing = _hatch(rule, f"layers.water.rules[{index}]")
            break
    return True, line, pattern, spacing


def place_dot_diameter(style):
    places = style.get("layers", {}).get("places")
    if places is None:
        sys.exit("gen_mapstyle.py: layers.places missing")
    if not places.get("enabled", True):
        print("gen_mapstyle.py: layers.places.enabled is false -- no place dots will be drawn")
        return 0
    diameter = 2 * _round_px(places.get("dot_radius_px", 0), "layers.places.dot_radius_px")
    if diameter > 255:
        sys.exit(f"gen_mapstyle.py: place dot diameter {diameter}px does not fit a uint8_t")
    return diameter


def marker_anchor(style):
    device = style.get("device")
    if device is None:
        sys.exit("gen_mapstyle.py: device block missing")
    x = _round_px(device.get("marker_x_px", 0), "device.marker_x_px")
    y = _round_px(device.get("marker_y_px", 0), "device.marker_y_px")
    # Off-panel is allowed for tuning (MapViewport.h's marker ladder comment
    # says so), but it must still fit the int16_t it is stored in.
    if x > 32767 or y > 32767:
        sys.exit(f"gen_mapstyle.py: marker anchor {x},{y} does not fit an int16_t")
    return x, y


def gen_cpp(widths, casings, buildings_px, water_px, dot_diameter, marker_x, marker_y, puck_px):
    id_to_name = {class_id: name for name, class_id in _CLASS_ID.items()}
    lines = [
        "#pragma once",
        "",
        f"// {_HEADER_NOTE}",
        "",
        '#include "MapStyle.h"',
        "",
        "// Designated initialisers on purpose: this file is generated, and a field",
        "// reordered in MapStyle.h must break the build rather than silently shift a",
        "// number into the wrong member (it did once, 2026-08-05).",
        "inline constexpr MapStyle kDefaultMapStyle = {",
        "    // Road width per MapClassId. 0 = not drawn.",
        "    .roadWidthPx =",
        "    {",
    ]
    for class_id in range(_CLASS_SLOTS):
        name = id_to_name.get(class_id, "(reserved)")
        lines.append(f"        {widths[class_id]},  // {class_id} {name}")
    lines += [
        "    },",
        "    // Casing per class, same indexing. 0 = solid black line.",
        "    .roadCasingPx =",
        "    {",
    ]
    for class_id in range(_CLASS_SLOTS):
        name = id_to_name.get(class_id, "(reserved)")
        lines.append(f"        {casings[class_id]},  // {class_id} {name}")
    radius, ring, arrow = puck_px
    b_enabled, b_outline, b_pattern, b_spacing = buildings_px
    w_enabled, w_line, w_pattern, w_spacing = water_px
    lines += [
        "    },",
        f"    .buildingsEnabled = {'true' if b_enabled else 'false'},",
        f"    .buildingOutlinePx = {b_outline},",
        f"    .buildingHatch = MapAreaFill::Pattern::{b_pattern},",
        f"    .buildingHatchSpacingPx = {b_spacing},",
        f"    .waterEnabled = {'true' if w_enabled else 'false'},",
        f"    .waterLinePx = {w_line},",
        f"    .waterHatch = MapAreaFill::Pattern::{w_pattern},",
        f"    .waterHatchSpacingPx = {w_spacing},",
        f"    .placeDotDiameterPx = {dot_diameter},",
        f"    .markerXPx = {marker_x},",
        f"    .markerYPx = {marker_y},",
        f"    .puckRadiusPx = {radius},",
        f"    .puckRingPx = {ring},",
        f"    .puckArrowPx = {arrow},",
        "};",
        "",
    ]
    return "\n".join(lines)


def main(repo_root, style_path=None, output_path=None):
    if style_path is None:
        style_path = os.path.join(repo_root, "data", "mapstyle.json")
    if output_path is None:
        output_path = os.path.join(repo_root, "src", "activities", "map", "MapStyleDefaults.h")

    if not os.path.isfile(style_path):
        sys.exit(f"gen_mapstyle.py: {style_path} not found")

    with open(style_path) as f:
        style = json.load(f)

    widths, casings = road_widths(style)
    buildings_px = buildings(style)
    water_px = water(style)
    dot_diameter = place_dot_diameter(style)
    marker_x, marker_y = marker_anchor(style)
    puck_px = puck(style)

    drawn = sum(1 for w in widths if w)
    cased = sum(1 for c in casings if c)
    print(f"gen_mapstyle.py: {drawn} road classes drawn, widths {min(w for w in widths if w)}"
          f"..{max(widths)}px, {cased} cased, place dot {dot_diameter}px, marker {marker_x},{marker_y}, "
          f"puck r{puck_px[0]}/ring{puck_px[1]}/arrow{puck_px[2]}")
    print(f"gen_mapstyle.py: buildings {'on' if buildings_px[0] else 'off'} "
          f"(outline {buildings_px[1]}px, hatch {buildings_px[2]}/{buildings_px[3]}px), "
          f"water {'on' if water_px[0] else 'off'} "
          f"(line {water_px[1]}px, hatch {water_px[2]}/{water_px[3]}px)")

    with open(output_path, "w") as f:
        f.write(gen_cpp(widths, casings, buildings_px, water_px, dot_diameter, marker_x, marker_y, puck_px))
    print(f"gen_mapstyle.py: wrote {output_path}")


# PlatformIO/SCons entry point -- Import and env are SCons builtins injected at
# runtime. `__file__` is not defined in that exec environment (the same trap
# git_branch.py and gen_mode_masks.py avoid the same way), so the repo root has
# to come from env rather than from this file's own path.
if __name__ == "__main__":
    _repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(_repo_root, *sys.argv[1:3])
else:
    try:
        Import("env")  # noqa: F821
        main(env["PROJECT_DIR"])  # noqa: F821
    except NameError:
        pass
