#!/usr/bin/env python3
"""Bake the map header status row's icons into src/components/icons/map_header_icons.h.

    python3 scripts/gen_map_header_icons.py

Same freeink::Icon output format as freeink-sdk/libs/assets/Icons/tools/gen_icons.py
(1bpp, MSB first, bit 1 = leave the pixel alone, bit 0 = ink, opticalCenterY =
content's centre of mass row), so GfxRenderer draws these the same way it draws
search24.h. Drawn with GfxRenderer::drawMono1bpp(), not drawIcon() -- the map
header renders in whatever orientation the device is held in, and drawIcon()
bakes in a quarter turn that assumes the forced-Portrait UI themes
(GfxRenderer.cpp, drawIcon()'s own comment).

Exists next to the SDK generator, not calling it, for the same reason
scripts/gen_home_icons.py does: it needs rsvg-convert, not on every machine
here, so this falls back to cairosvg. 14px is the map header's own row height
(MapActivity.cpp, kHeaderIconHeight), not a knob.
"""
import io
import os
import re
import shutil
import subprocess
import sys

from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUCIDE = os.path.join(REPO, "freeink-sdk/libs/assets/Icons/lucide/icons")
OUT = os.path.join(REPO, "src/components/icons/map_header_icons.h")

THRESHOLD = 110
ROW_SIZE = 14

# alias -> lucide name.
LUCIDE_ICONS = [
    ("transferBle", "arrow-left-right", ROW_SIZE),
    # The GNSS receiver's three states, one glyph each. Same family on purpose:
    # the rider reads the difference between them, not each one from scratch.
    ("gnssOff", "locate-off", ROW_SIZE),
    ("gnssSearching", "locate", ROW_SIZE),
    ("gnssFixed", "locate-fixed", ROW_SIZE),
]


def rasterise(svg_path, width, height):
    if shutil.which("rsvg-convert"):
        png = subprocess.run(
            ["rsvg-convert", "-w", str(width), "-h", str(height), svg_path],
            capture_output=True,
            check=True,
        ).stdout
    else:
        import cairosvg

        png = cairosvg.svg2png(url=svg_path, output_width=width, output_height=height)
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    flat = Image.new("RGBA", img.size, (255, 255, 255, 255))
    flat.paste(img, mask=img.split()[3])
    return flat.convert("L")


def pack(img):
    """-> (bytes, opticalCenterY). 1 = transparent, 0 = ink, MSB first."""
    width, height = img.size
    pixels = img.load()
    data = []
    sum_y = 0
    count = 0
    for y in range(height):
        for x_byte in range(0, width, 8):
            byte = 0
            for bit in range(8):
                x = x_byte + bit
                white = 1
                if x < width and pixels[x, y] < THRESHOLD:
                    white = 0
                    sum_y += y
                    count += 1
                byte |= white << (7 - bit)
            data.append(byte)
    return data, (round(sum_y / count) if count else height // 2)


def ident(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def emit(alias, img, note):
    data, centre = pack(img)
    width, height = img.size
    bits = f"icon_{ident(alias)}_bits"
    body = ", ".join(f"0x{b:02X}" for b in data)
    return [
        f"// {note}",
        f"static const uint8_t {bits}[] = {{{body}}};",
        f"static const freeink::Icon icon_{ident(alias)} = "
        f"{{{width}, {height}, {centre}, {bits}}};",
        "",
    ]


def main():
    out = [
        "#pragma once",
        "",
        "#include <Icon.h>",
        "",
        "#include <cstdint>",
        "",
        "// Generated by scripts/gen_map_header_icons.py. Do not edit.",
        f"// {ROW_SIZE}px, drawn with GfxRenderer::drawMono1bpp() (not drawIcon() --",
        "// see the script's own header comment for why).",
        "",
    ]

    for alias, lucide, size in LUCIDE_ICONS:
        svg = os.path.join(LUCIDE, lucide + ".svg")
        if not os.path.exists(svg):
            sys.exit(f"missing svg for '{alias}': {svg}")
        out += emit(alias, rasterise(svg, size, size), f"{alias}  (lucide: {lucide})")

    with open(OUT, "w") as handle:
        handle.write("\n".join(out))
    if shutil.which("clang-format"):
        subprocess.run(["clang-format", "-i", OUT], check=True)
    else:
        print("warning: clang-format not found -- run it on the output before committing")
    print(f"wrote {OUT}: {len(LUCIDE_ICONS)} icons")


if __name__ == "__main__":
    main()
