#!/usr/bin/env python3
"""
Generate the compiled ride/hike/cycle mode masks from data/mapstyle.json's
`modes` block.

MapModeMaskDefaults.h is a build product, like lib/I18n/I18nKeys.h -- gitignored,
regenerated on every build (wired as a pre: step in platformio.ini next to
gen_i18n.py and build_html.py). data/mapstyle.json is the source: it already
lives in this repo and is the device's definitive style, so the firmware
builds standalone with nothing read from outside it.

The style is authored in the separate laptop-side tooling repo (its webapp
writes this data/mapstyle.json directly) -- that direction crosses repos on
purpose, but nothing here reads back across that boundary. See
docs/mapstyle.json.md.

Usage:
    python3 scripts/gen_mode_masks.py [style_path [output_path]]

Defaults: data/mapstyle.json -> src/activities/map/MapModeMaskDefaults.h.
"""
import importlib.util
import json
import os
import sys

# scripts/mapstyle_variants.py, loaded by path -- see the same helper in
# gen_mapstyle.py for why a plain import cannot work under SCons.
mapstyle_variants = None


def _load_variants(repo_root):
    global mapstyle_variants
    if mapstyle_variants is not None:
        return
    path = os.path.join(repo_root, "scripts", "mapstyle_variants.py")
    spec = importlib.util.spec_from_file_location("mapstyle_variants", path)
    if spec is None or spec.loader is None:
        sys.exit(f"gen_mode_masks.py: cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    mapstyle_variants = module

# Fixed order, independent of the JSON's key order -- this is what
# MapRideMode (Ride=0, Hike=1, Cycle=2) and MapModeMasks's default array
# assume.
_MODE_ORDER = ["ride", "hike", "cycle"]

# The tile format's own class_id enum (mapbuilder/tilegen/class_spec.py, mirrored in
# MapClassEnum.h). Owned by the tile format, not by the style -- duplicated
# here rather than imported because nothing outside this repo may be read to
# build this repo, and this list is a one-way door the same way the tile
# format's is (docs/map-data-spec.md, "The class enum").
_CLASS_ID = {
    "unknown": 0,
    "motorway": 1,
    "trunk": 2,
    "primary": 3,
    "secondary": 4,
    "tertiary": 5,
    "unclassified": 6,
    "residential": 7,
    "living_street": 8,
    "service": 9,
    "pedestrian": 10,
    "track": 11,
    "bridleway": 12,
    "cycleway": 13,
    "footway": 14,
    "path": 15,
    "steps": 16,
    "construction": 17,
    "ferry": 18,
    "railway": 19,
    "aerialway": 20,
}

_HEADER_NOTE = "Generated by scripts/gen_mode_masks.py from data/mapstyle.json. Do not hand-edit."


def compute_masks(style):
    """Returns {mode_name: mask}, or exits the build on any bad input.

    Fatal, not warn-and-continue: this is a generated file, and a mistake
    that only warns is a mistake that ships. An unknown class name or an
    empty mask are both build errors, never a 0x00000000 that draws nothing
    and looks like a broken card (docs/map-data-spec.md, "Mode is a
    render-time filter").
    """
    modes = style.get("modes", {})
    masks = {}
    for mode_name in _MODE_ORDER:
        classes = modes.get(mode_name, {}).get("classes", [])
        mask = 0
        for name in classes:
            if name not in _CLASS_ID:
                sys.exit(f"gen_mode_masks.py: mode '{mode_name}': unknown class '{name}'")
            mask |= 1 << _CLASS_ID[name]
        if mask == 0:
            sys.exit(f"gen_mode_masks.py: mode '{mode_name}' resolves to an empty class mask "
                      f"-- a mode that draws no roads is never what a style file means")
        masks[mode_name] = mask
    return masks


def drawn_mask(resolved):
    """Bits for the classes this resolved style actually draws.

    Mirrors gen_mapstyle.py's road_widths() exactly: a visible class is forced
    to at least 1 px there, so "drawn" is precisely "the roads layer is on and
    no rule hides this class". Keep the two in step -- if they disagree, the
    device pays a card read and a projection for a way it then draws at width 0.
    """
    roads = resolved.get("layers", {}).get("roads", {})
    if not roads.get("enabled", True):
        return 0
    mask = 0
    for class_id in _CLASS_ID.values():
        mask |= 1 << class_id
    for index, rule in enumerate(roads.get("rules", [])):
        if not rule.get("hidden", False):
            continue
        for name in rule.get("match", {}).get("class", []):
            if name not in _CLASS_ID:
                sys.exit(f"gen_mode_masks.py: layers.roads.rules[{index}]: unknown class '{name}'")
            mask &= ~(1 << _CLASS_ID[name])
    return mask


def compute_table(style):
    """masks[mode][rung] -- what the tile reader lets through.

    Two filters, intersected, and the intersection is the point. `modes` says
    which classes a travel mode cares about at all; the style's `hidden` says
    which ones this rung draws. Before they were intersected, a class the style
    hid was still read off the card and projected, then drawn at width 0 -- the
    whole cost and none of the picture. Intersecting also makes it impossible
    for the filter and the style to disagree, which is a bug that would look
    like a missing road and read like a corrupt tile.
    """
    table = []
    for mode_name in _MODE_ORDER:
        row = []
        for step in range(mapstyle_variants.ZOOM_STEPS):
            try:
                resolved = mapstyle_variants.resolve(style, mode_name, step)
            except mapstyle_variants.VariantError as error:
                sys.exit(f"gen_mode_masks.py: {mode_name}@{step}: {error}")
            mask = compute_masks(resolved)[mode_name] & drawn_mask(resolved)
            if mask == 0:
                sys.exit(f"gen_mode_masks.py: {mode_name}@rung {step} resolves to an empty class mask "
                         f"-- a rung that draws no roads at all is never what a style file means")
            row.append(mask)
        table.append(row)
    return table


def gen_cpp(base_masks, table):
    lines = [
        "#pragma once",
        "",
        f"// {_HEADER_NOTE}",
        "",
        "#include <cstdint>",
        "",
        '#include "MapRideMode.h"',
        "",
        "// The per-mode class lists on their own, with no rung applied. Kept",
        "// because a mode's own vocabulary is a real thing to test against and",
        "// to print in a diagnostic; the renderer uses the table below.",
    ]
    for mode_name in _MODE_ORDER:
        cpp_name = "".join(p.capitalize() for p in mode_name.split("_"))
        lines.append(f"inline constexpr uint32_t kDefault{cpp_name}Mask = 0x{base_masks[mode_name]:08x}u;")
    lines += [
        "",
        "// What MapTileSource filters with: the mode's classes intersected with the",
        "// classes that rung's style actually draws. A way outside it is not read",
        "// past its header, so a class hidden at a coarse rung costs nothing at all.",
        "inline constexpr uint32_t kMapModeMasks[kMapRideModeCount][kMapZoomStepCount] = {",
    ]
    for mode_index, mode_name in enumerate(_MODE_ORDER):
        row = ", ".join(f"0x{mask:08x}u" for mask in table[mode_index])
        lines.append(f"    {{{row}}},  // {mode_name}")
    lines += ["};", ""]
    return "\n".join(lines)


def main(repo_root, style_path=None, output_path=None):
    if style_path is None:
        style_path = os.path.join(repo_root, "data", "mapstyle.json")
    if output_path is None:
        output_path = os.path.join(repo_root, "src", "activities", "map", "MapModeMaskDefaults.h")

    _load_variants(repo_root)

    if not os.path.isfile(style_path):
        sys.exit(f"gen_mode_masks.py: {style_path} not found")

    with open(style_path) as f:
        style = json.load(f)

    try:
        base_masks = compute_masks(mapstyle_variants.base(style))
    except mapstyle_variants.VariantError as error:
        sys.exit(f"gen_mode_masks.py: {error}")
    table = compute_table(style)
    id_to_name = {class_id: name for name, class_id in _CLASS_ID.items()}
    for mode_index, mode_name in enumerate(_MODE_ORDER):
        rungs = " ".join(f"0x{mask:08x}" for mask in table[mode_index])
        print(f"gen_mode_masks.py: {mode_name} base 0x{base_masks[mode_name]:08x} | per rung {rungs}")
        # A class the mode asks for and the style hides at every rung is not a
        # bug, but it is always a surprise -- `modes` reads like the list of
        # what a mode draws, and it is only half of it. Say so rather than
        # letting the two disagree quietly.
        drawn_anywhere = 0
        for step_mask in table[mode_index]:
            drawn_anywhere |= step_mask
        never = base_masks[mode_name] & ~drawn_anywhere
        if never:
            hidden = ", ".join(id_to_name[bit] for bit in sorted(id_to_name) if never & (1 << bit))
            print(f"gen_mode_masks.py: note -- {mode_name} lists {hidden}, but the style hides "
                  f"{'them' if never & (never - 1) else 'it'} at every rung, so nothing is drawn")

    with open(output_path, "w") as f:
        f.write(gen_cpp(base_masks, table))
    print(f"gen_mode_masks.py: wrote {output_path}")


# PlatformIO/SCons entry point -- Import and env are SCons builtins injected at
# runtime. `__file__` is not defined in that exec environment (the same trap
# git_branch.py avoids the same way), so the repo root has to come from env
# rather than from this file's own path.
if __name__ == "__main__":
    _repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(_repo_root, *sys.argv[1:3])
else:
    try:
        Import("env")  # noqa: F821
        main(env["PROJECT_DIR"])  # noqa: F821
    except NameError:
        pass
