#!/usr/bin/env python3
"""Bake src/images/home-header.svg into src/images/HomeHeader.h.

    python3 scripts/gen_home_header.py

The header is the Home screen's brand block: traced mountain line art with the
logo mark and the ExplorInk wordmark over it. One bitmap, one drawImage() call,
no runtime layout -- edit the SVG and re-run this.

Why not convert_icon.py: that one takes a width/height off the command line and
only ever wrote square icons into src/components/icons/. This asset is 480x224,
lives in src/images/, and its size is a property of the panel (480 px wide), not
a knob.

Two constraints come from GfxRenderer::drawImage() (see docs/sleep-screen.md,
"The wordmark image"): it rotates the *origin* for the current orientation but
not the pixel data, and the low-level blit indexes the source as w/8 bytes per
row. So the buffer is written pre-rotated 90 degrees -- raw 224x480 for art
authored 480x224 -- and the raw width (224) must be a multiple of 8.

Threshold, not dithering: at 480 px the traced lines are 1-2 px wide, and
dithering eats them (measured -- ink drops from 13.8% to 10.0% and the wordmark
edges go ragged). 215 keeps the faint ridge lines and the valley trail.
"""
import io
import os
import sys

import cairosvg
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SVG = os.path.join(REPO, "src/images/home-header.svg")
OUT = os.path.join(REPO, "src/images/HomeHeader.h")

# Authored (on-screen) size in device pixels. The panel is 480 wide.
WIDTH = 480
HEIGHT = 224
THRESHOLD = 215


def rasterise(svg_path, width, height):
    png = cairosvg.svg2png(url=svg_path, output_width=width, output_height=height)
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    flat = Image.new("RGBA", img.size, (255, 255, 255, 255))
    flat.paste(img, mask=img.split()[3])
    return flat.convert("L")


def pack(img, name):
    """1bpp, MSB first, 1 = white -- the convention every image in src/images uses."""
    width, height = img.size
    pixels = img.tobytes()  # L mode: one byte per pixel, row-major
    out = bytearray()
    for y in range(height):
        for x in range(0, width, 8):
            byte = 0
            for bit in range(8):
                if x + bit < width and pixels[y * width + x + bit] >= THRESHOLD:
                    byte |= 1 << (7 - bit)
            out.append(byte)
    body = ""
    for i, value in enumerate(out):
        body += f"0x{value:02X}, "
        if (i + 1) % 16 == 0:
            body += "\n    "
    return (
        "#pragma once\n#include <cstdint>\n\n"
        f"// Generated by scripts/gen_home_header.py from src/images/home-header.svg.\n"
        f"// Raw buffer: {width}x{height} (pre-rotated 90 deg). drawImage()'s width/height\n"
        f"// args must be {width}, {height}; on screen in Portrait this reads as the\n"
        f"// header at its authored {WIDTH}x{HEIGHT}.\n"
        f"#define HOMEHEADER_WIDTH {width}\n"
        f"#define HOMEHEADER_HEIGHT {height}\n"
        f"#define HOMEHEADER_ON_SCREEN_WIDTH {WIDTH}\n"
        f"#define HOMEHEADER_ON_SCREEN_HEIGHT {HEIGHT}\n"
        f"static const uint8_t {name}[] = {{\n    " + body.rstrip(", \n") + "\n};\n"
    )


def main():
    if not os.path.exists(SVG):
        sys.exit(f"missing {SVG}")
    img = rasterise(SVG, WIDTH, HEIGHT)
    img = img.rotate(90, expand=True)  # same convention as convert_icon.py
    if img.size[0] % 8:
        sys.exit(f"raw width {img.size[0]} is not a multiple of 8 -- drawImage truncates w/8")
    with open(OUT, "w") as handle:
        handle.write(pack(img, "HomeHeader"))
    print(f"Wrote {OUT} ({os.path.getsize(OUT) // 1024} kB source, "
          f"{WIDTH * HEIGHT // 8 // 1024} kB flash)")


if __name__ == "__main__":
    main()
