#!/usr/bin/env python3
"""
Generate the compiled MapStyle instance from data/mapstyle.json.

MapStyleDefaults.h is a build product, like MapModeMaskDefaults.h and
lib/I18n/I18nKeys.h -- gitignored, regenerated on every build (wired as a
pre: step in platformio.ini, and as a CMake custom command for the host
build in test/CMakeLists.txt). data/mapstyle.json is the source: it lives in
this repo and is the device's definitive style, so the firmware builds
standalone with nothing read from outside it.

Because the host build regenerates from the same file, editing the style in
mapbuilder's webapp and rebuilding test/map_preview shows the change without
flashing anything. See docs/mapstyle.json.md.

Usage:
    python3 scripts/gen_mapstyle.py [style_path [output_path]]

Defaults: data/mapstyle.json -> src/activities/map/MapStyleDefaults.h.
"""
import importlib.util
import json
import os
import sys

# scripts/mapstyle_variants.py, loaded by path rather than imported by name.
# Under PlatformIO this file is exec'd by SCons with no `__file__` and with
# scripts/ nowhere on sys.path, so a plain `import` works from the command
# line and fails in the build -- the same trap the SCons entry point at the
# bottom already documents. main() always knows the repo root, so the load
# happens there and this stays a plain module reference everywhere else.
mapstyle_variants = None


def _load_variants(repo_root):
    global mapstyle_variants
    if mapstyle_variants is not None:
        return
    path = os.path.join(repo_root, "scripts", "mapstyle_variants.py")
    spec = importlib.util.spec_from_file_location("mapstyle_variants", path)
    if spec is None or spec.loader is None:
        sys.exit(f"gen_mapstyle.py: cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    mapstyle_variants = module

# The tile format's own class_id enum (mapbuilder/tilegen/class_spec.py, mirrored in
# MapClassEnum.h). Duplicated here for the same reason gen_mode_masks.py
# duplicates it: nothing outside this repo may be read to build this repo.
_CLASS_ID = {
    "unknown": 0,
    "motorway": 1,
    "trunk": 2,
    "primary": 3,
    "secondary": 4,
    "tertiary": 5,
    "unclassified": 6,
    "residential": 7,
    "living_street": 8,
    "service": 9,
    "pedestrian": 10,
    "track": 11,
    "bridleway": 12,
    "cycleway": 13,
    "footway": 14,
    "path": 15,
    "steps": 16,
    "construction": 17,
    "ferry": 18,
    "railway": 19,
    "aerialway": 20,
}

# MapClassEnum.h's kClassEnumSlots -- the array length MapStyle declares.
_CLASS_SLOTS = 32

# The area layers' own small class enums (MapAreaClass.h, mirroring
# mapbuilder/tilegen/water_class.py and landuse_class.py). Not slots in the road enum:
# a record's layer id already says which vocabulary its class byte belongs to.
_WATER_CLASS = {"unknown": 0, "river": 1, "stream": 2, "lake": 3}
_LANDUSE_CLASS = {"forest": 1, "built_up": 2}
_WATER_SLOTS = 4
_LANDUSE_SLOTS = 4

def _toneLabel(expr):
    """The summary lines are read by a human tuning a style, so print `micro`
    rather than `MapTone::dots(4, false)`."""
    text = str(expr)
    if text.startswith("MapAreaTone::"):
        return text[len("MapAreaTone::"):].lower()
    if text.startswith("MapTone::dots("):
        inner = text[len("MapTone::dots("):-1]
        period, stagger = [part.strip() for part in inner.split(",")]
        return f"dots/{period}" + ("+stagger" if stagger == "true" else "")
    return text


_HEADER_NOTE = "Generated by scripts/gen_mapstyle.py from data/mapstyle.json. Do not hand-edit."


def _round_px(value, what):
    """Style lengths are floats; the canvas takes int pixels. Round half up.

    Python's round() is banker's rounding, which would turn a 2.5px casing
    into 2 and a 3.5px one into 4 -- not what a style author reading the
    file would predict.
    """
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        sys.exit(f"gen_mapstyle.py: {what}: expected a number, got {value!r}")
    if value < 0:
        sys.exit(f"gen_mapstyle.py: {what}: negative length {value}")
    return int(value + 0.5)


def road_widths(style):
    """Returns (widths, casings), each kClassEnumSlots long, indexed by class_id.

    A class with no rule of its own gets layers.roads.default's width, which
    is what the laptop-side renderer does (mapbuilder/style.py resolve_rule).
    A hidden class, and every reserved enum slot, gets width 0 -- MapRenderer
    skips those without drawing.
    """
    roads = style.get("layers", {}).get("roads")
    if roads is None:
        sys.exit("gen_mapstyle.py: layers.roads missing")

    widths = [0] * _CLASS_SLOTS
    casings = [0] * _CLASS_SLOTS
    patterns = ["Solid"] * _CLASS_SLOTS
    dashes = [0] * _CLASS_SLOTS
    gaps = [0] * _CLASS_SLOTS
    tones = ["MapAreaTone::None"] * _CLASS_SLOTS
    if not roads.get("enabled", True):
        print("gen_mapstyle.py: layers.roads.enabled is false -- no roads will be drawn")
        return widths, casings, patterns, dashes, gaps, tones

    default_width = _round_px(roads.get("default", {}).get("width", 1), "layers.roads.default.width")
    for class_id in _CLASS_ID.values():
        widths[class_id] = max(default_width, 1)

    for index, rule in enumerate(roads.get("rules", [])):
        classes = rule.get("match", {}).get("class", [])
        for name in classes:
            if name not in _CLASS_ID:
                sys.exit(f"gen_mapstyle.py: layers.roads.rules[{index}]: unknown class '{name}'")
            if rule.get("hidden", False):
                widths[_CLASS_ID[name]] = 0
                casings[_CLASS_ID[name]] = 0
                patterns[_CLASS_ID[name]] = "Solid"
                dashes[_CLASS_ID[name]] = 0
                gaps[_CLASS_ID[name]] = 0
                tones[_CLASS_ID[name]] = "MapAreaTone::None"
                continue
            width = _round_px(rule.get("width", default_width), f"layers.roads.rules[{index}].width")
            # A visible class must stay visible. Rounding 0.4px to 0 would
            # silently delete a road class that the style file draws.
            width = max(width, 1)
            if width > 255:
                sys.exit(f"gen_mapstyle.py: class '{name}' width {width}px does not fit a uint8_t")
            widths[_CLASS_ID[name]] = width

            casing = _round_px(rule.get("casing_px", 0), f"layers.roads.rules[{index}].casing_px")
            # Two casings plus at least one white pixel between them, or there
            # is no white left and the "casing" is just a solid black line
            # drawn the slow way, in two passes.
            if casing > 0 and 2 * casing >= width:
                casing = 0
                print(f"gen_mapstyle.py: class '{name}': casing_px leaves no white inside a {width}px "
                      f"road -- drawing it solid instead")
            casings[_CLASS_ID[name]] = casing
            (patterns[_CLASS_ID[name]], dashes[_CLASS_ID[name]],
             gaps[_CLASS_ID[name]]) = _dash(rule, f"layers.roads.rules[{index}]")

            # `fill: tone` shades the inside of a cased road instead of leaving
            # it white -- a paper map's motorway, a thin outline around a
            # shaded ribbon. Refused where it cannot show: with no casing there
            # is no interior at all, and an interior under 2 px cannot carry a
            # period-2 pattern. Refused rather than ignored, because a style
            # that silently draws nothing is the bug this file keeps hitting.
            tone = _tone(rule, f"layers.roads.rules[{index}]")
            if tone != "MapAreaTone::None":
                if casing == 0:
                    sys.exit(f"gen_mapstyle.py: class '{name}': `fill: tone` needs a casing -- with "
                             f"none, the road is solid black and has no interior to shade")
                if width - 2 * casing < 2:
                    sys.exit(f"gen_mapstyle.py: class '{name}': `fill: tone` needs an interior of at "
                             f"least 2px, but {width}px with a {casing}px casing leaves "
                             f"{width - 2 * casing}px")
            tones[_CLASS_ID[name]] = tone

    if not any(widths):
        sys.exit("gen_mapstyle.py: every road class resolves to width 0 -- a style that draws no "
                 "roads at all is never what a style file means")
    return widths, casings, patterns, dashes, gaps, tones


def puck(style):
    """(radius, ring, arrow) for layers.position, in px.

    Disabled means radius 0, which MapRenderer reads as "no disc, arrow only".
    The arrow is kept either way: a position that draws nothing is never what
    a style file means.
    """
    position = style.get("layers", {}).get("position", {})
    arrow = _round_px(position.get("arrow_px", 28), "layers.position.arrow_px")
    if not position.get("enabled", True):
        print("gen_mapstyle.py: layers.position.enabled is false -- arrow only, no puck disc")
        return 0, 0, arrow
    radius = _round_px(position.get("puck_radius_px", 0), "layers.position.puck_radius_px")
    ring = _round_px(position.get("ring_px", 0), "layers.position.ring_px")
    if radius and ring >= radius:
        sys.exit(f"gen_mapstyle.py: layers.position.ring_px {ring} leaves no white disc inside "
                 f"puck_radius_px {radius}")
    for name, value in (("puck_radius_px", radius), ("ring_px", ring), ("arrow_px", arrow)):
        if value > 255:
            sys.exit(f"gen_mapstyle.py: layers.position.{name} {value}px does not fit a uint8_t")
    return radius, ring, arrow


# mapstyle.json's hatch strings are matplotlib's. Only the character matters
# here; the repeat count ("XXXX") is a matplotlib density knob, and density on
# the device comes from hatch_spacing_px, in device pixels like every other
# length. Maps to MapAreaFill::Pattern.
# mapstyle.json's `pattern` finally reaches the device. Dash length in device
# pixels; the gap matches it. "dotted" is a short dash, not a single pixel --
# one pixel on and one off is a grey line at arm's length, not a dotted one.
_LINE_DASH_PX = {
    "solid": (0, 0),
    "dashed": (6, 4),
    "dotted": (2, 3),
    # Short marks with long spaces, laid across a line that stays whole --
    # the sleepers of a railway. The opposite rhythm to a dash, which is why
    # it cannot be expressed by tuning "dashed".
    "ticked": (2, 8),
}


def _dash(rule, what):
    """(dash length, gap length) in px. 0/0 means a solid stroke."""
    pattern = str(rule.get("pattern", "solid")).strip().lower()
    if pattern not in _LINE_DASH_PX:
        sys.exit(f"gen_mapstyle.py: {what}: pattern '{pattern}' is not one of "
                 f"{sorted(_LINE_DASH_PX)}")
    dash, gap = _LINE_DASH_PX[pattern]
    kind = {"solid": "Solid", "dashed": "Dashed", "dotted": "Dashed", "ticked": "Ticked"}[pattern]
    if rule.get("dash_px") is not None:
        dash = _round_px(rule["dash_px"], f"{what}.dash_px")
    if rule.get("gap_px") is not None:
        gap = _round_px(rule["gap_px"], f"{what}.gap_px")
    for value, field in ((dash, "dash_px"), (gap, "gap_px")):
        if value > 255:
            sys.exit(f"gen_mapstyle.py: {what}: {field} {value} does not fit a uint8_t")
    if dash > 0 and gap <= 0:
        sys.exit(f"gen_mapstyle.py: {what}: a dash with no gap is a solid line -- "
                 f"use pattern 'solid' or give gap_px above 0")
    return kind, dash, gap


_HATCH_PATTERN = {
    "/": "Diagonal",
    "\\": "AntiDiagonal",
    "-": "Horizontal",
    "|": "Vertical",
    "~": "Wave",
    "X": "Cross",
    "x": "Cross",
    "+": "Cross",
}


# mapstyle.json's `tone` names, mapped to MapAreaTone. A tone is a screen-space
# pixel pattern that reads as grey from arm's length -- what a built-up area
# wants. See the firmware's docs/map-style.md.
# Named tones, and the shorthands for the dot grids. `dots` with an explicit
# `tone_period_px` covers everything else -- see _tone().
_TONES = {
    "light": "MapAreaTone::Light",
    "dark": "MapAreaTone::Dark",
    "solid": "MapAreaTone::Solid",
    "dense": "MapAreaTone::Dense",
    "dense_stagger": "MapAreaTone::DenseStagger",
    "stipple": "MapAreaTone::Stipple",
    "stipple_stagger": "MapAreaTone::StippleStagger",
    "micro": "MapAreaTone::Micro",
    "micro_stagger": "MapAreaTone::MicroStagger",
}

# MapAreaTone.h packs a dot grid's period into the tone value, so a style can name
# a density directly. Bounds are that packing's, not a taste judgement: 1 would be
# `solid` and 16 does not fit.
_DOT_PERIOD_MIN = 2
_DOT_PERIOD_MAX = 15


def _tone(rule, what):
    """The C++ expression for a rule's tone, or MapAreaTone::None.

    `tone: dots` reads `tone_period_px` and `tone_stagger` and emits the packed
    value. Every other name is a fixed pattern or a shorthand for a dot grid, and
    a shorthand must not also carry a period -- two ways of saying the same thing,
    free to disagree, is what this file exists to avoid.
    """
    if rule.get("fill") != "tone":
        return "MapAreaTone::None"
    name = str(rule.get("tone", "")).strip().lower()
    has_period = "tone_period_px" in rule
    if name == "dots":
        if not has_period:
            sys.exit(f"gen_mapstyle.py: {what}: tone 'dots' needs tone_period_px "
                     f"({_DOT_PERIOD_MIN}..{_DOT_PERIOD_MAX}); a named tone like 'micro' if you "
                     f"want a fixed one")
        period = _round_px(rule.get("tone_period_px"), f"{what}.tone_period_px")
        if not _DOT_PERIOD_MIN <= period <= _DOT_PERIOD_MAX:
            sys.exit(f"gen_mapstyle.py: {what}: tone_period_px {period} is outside "
                     f"{_DOT_PERIOD_MIN}..{_DOT_PERIOD_MAX}. 1 is `solid`, and anything above "
                     f"{_DOT_PERIOD_MAX} does not fit the packed tone value (MapAreaTone.h)")
        stagger = "true" if rule.get("tone_stagger", False) else "false"
        return f"MapTone::dots({period}, {stagger})"
    if name not in _TONES:
        sys.exit(f"gen_mapstyle.py: {what}: fill is tone but tone '{name}' is not one of "
                 f"{sorted(_TONES) + ['dots']}")
    if has_period:
        sys.exit(f"gen_mapstyle.py: {what}: tone '{name}' is a named density, so tone_period_px "
                 f"has nothing to do. Use tone 'dots' to set one.")
    return _TONES[name]


def _hatch(rule, what):
    """(pattern enum name, spacing px) for a layer rule's fill.

    A rule with no `fill: hatch` draws no fill at all -- outline only, or
    nothing if the outline is 0 too. That is a legitimate style, so it is not
    an error.
    """
    if rule.get("fill") != "hatch":
        return "None", 0
    text = str(rule.get("hatch", "")).strip()
    if not text:
        sys.exit(f"gen_mapstyle.py: {what}: fill is hatch but no hatch pattern given")
    pattern = _HATCH_PATTERN.get(text[0])
    if pattern is None:
        sys.exit(f"gen_mapstyle.py: {what}: hatch '{text}' starts with a character this renderer "
                 f"has no pattern for (use one of {''.join(sorted(_HATCH_PATTERN))})")
    spacing = _round_px(rule.get("hatch_spacing_px", 0), f"{what}.hatch_spacing_px")
    if spacing <= 0:
        sys.exit(f"gen_mapstyle.py: {what}: hatch needs a hatch_spacing_px above 0 "
                 f"-- spacing 0 would be a solid fill, which 1-bit cannot afford")
    if spacing > 255:
        sys.exit(f"gen_mapstyle.py: {what}: hatch_spacing_px {spacing} does not fit a uint8_t")
    return pattern, spacing


def buildings(style):
    """(enabled, outline px, tone, hatch pattern, hatch spacing)."""
    layer = style.get("layers", {}).get("buildings", {})
    if not layer.get("enabled", False):
        return False, 0, "MapAreaTone::None", "None", 0
    rule = layer.get("rule", {})
    outline = _round_px(rule.get("outline_width", 0), "layers.buildings.rule.outline_width")
    tone = _tone(rule, "layers.buildings.rule")
    pattern, spacing = _hatch(rule, "layers.buildings.rule")
    if outline == 0 and pattern == "None" and tone == "MapAreaTone::None":
        sys.exit("gen_mapstyle.py: layers.buildings is enabled but draws neither an outline, a tone nor a "
                 "hatch -- that reads every building off the card to draw nothing. Disable the layer instead.")
    return True, outline, tone, pattern, spacing


def water(style):
    """(enabled, [width per water class], tone, hatch pattern, hatch spacing).

    Widths are per class now (river, stream, lake, unknown) -- the builder
    started writing a water class byte on 2026-08-05. Rules key on `class`, the
    same vocabulary the tile carries, not on raw OSM tags: matching `waterway:
    river` here would be a second vocabulary that cannot be checked against
    anything (docs/map-data-spec.md, "One vocabulary, not two").

    The area tone or hatch comes from whichever rule carries a `fill`; only the
    lake class ever arrives as a ring.
    """
    layer = style.get("layers", {}).get("water", {})
    widths = [0] * _WATER_SLOTS
    if not layer.get("enabled", False):
        return (False, widths, [0] * _WATER_SLOTS, ["Solid"] * _WATER_SLOTS, [0] * _WATER_SLOTS,
                [0] * _WATER_SLOTS, "MapAreaTone::None", "None", 0, False)

    default_width = max(_round_px(layer.get("default", {}).get("width", 1), "layers.water.default.width"), 1)
    for class_id in _WATER_CLASS.values():
        widths[class_id] = default_width

    patterns_w = ["Solid"] * _WATER_SLOTS
    outlines = [0] * _WATER_SLOTS
    dashes = [0] * _WATER_SLOTS
    gaps = [0] * _WATER_SLOTS
    tone, pattern, spacing, white = "MapAreaTone::None", "None", 0, False
    for index, rule in enumerate(layer.get("rules", [])):
        what = f"layers.water.rules[{index}]"
        classes = rule.get("match", {}).get("class")
        if classes is None:
            sys.exit(f"gen_mapstyle.py: {what}: water rules must match on `class` "
                     f"({sorted(_WATER_CLASS)}), not on OSM tags -- the tile carries the class, not the tags")
        for name in classes:
            if name not in _WATER_CLASS:
                sys.exit(f"gen_mapstyle.py: {what}: unknown water class '{name}' "
                         f"(one of {sorted(_WATER_CLASS)})")
            width = max(_round_px(rule.get("width", default_width), f"{what}.width"), 1)
            if width > 255:
                sys.exit(f"gen_mapstyle.py: {what}: width {width}px does not fit a uint8_t")
            widths[_WATER_CLASS[name]] = 0 if rule.get("hidden", False) else width
            # The ring border of a water *area*. Defaults to the class's line
            # width, which is what it was before this field existed, so a style
            # that says nothing draws exactly what it drew.
            outline = _round_px(rule.get("outline_width", width), f"{what}.outline_width")
            if outline > 255:
                sys.exit(f"gen_mapstyle.py: {what}: outline_width {outline}px does not fit a uint8_t")
            outlines[_WATER_CLASS[name]] = 0 if rule.get("hidden", False) else outline
            (patterns_w[_WATER_CLASS[name]], dashes[_WATER_CLASS[name]],
             gaps[_WATER_CLASS[name]]) = _dash(rule, what)
        # Water is the one layer that wants a tone *and* a pattern: a surface
        # dense enough to read as water, with waves knocked out of it in white.
        # Everywhere else `fill` picks one or the other, so both are read here
        # rather than switching on it.
        if rule.get("tone") and tone == "MapAreaTone::None":
            tone = _tone(dict(rule, fill="tone"), what)
        if rule.get("hatch") and pattern == "None":
            pattern, spacing = _hatch(dict(rule, fill="hatch"), what)
            if rule.get("hatch_white"):
                white = True
    return True, widths, outlines, patterns_w, dashes, gaps, tone, pattern, spacing, white


def landuse(style):
    """(enabled, [outline], [tone], [hatch], [spacing]) per landuse class.

    Forest and built-up share one tile layer and are drawn at different depths,
    so each class gets its own numbers and the renderer walks the layer once per
    class.
    """
    layer = style.get("layers", {}).get("landuse", {})
    outlines = [0] * _LANDUSE_SLOTS
    outline_dashes = [0] * _LANDUSE_SLOTS
    outline_gaps = [0] * _LANDUSE_SLOTS
    tones = ["MapAreaTone::None"] * _LANDUSE_SLOTS
    patterns = ["None"] * _LANDUSE_SLOTS
    spacings = [0] * _LANDUSE_SLOTS
    if not layer.get("enabled", False):
        return False, outlines, outline_dashes, outline_gaps, tones, patterns, spacings

    for index, rule in enumerate(layer.get("rules", [])):
        what = f"layers.landuse.rules[{index}]"
        classes = rule.get("match", {}).get("class")
        if classes is None:
            sys.exit(f"gen_mapstyle.py: {what}: landuse rules must match on `class` "
                     f"({sorted(_LANDUSE_CLASS)})")
        for name in classes:
            if name not in _LANDUSE_CLASS:
                sys.exit(f"gen_mapstyle.py: {what}: unknown landuse class '{name}' "
                         f"(one of {sorted(_LANDUSE_CLASS)})")
            class_id = _LANDUSE_CLASS[name]
            # `hidden` is how a rung switches a landuse class off without
            # deleting its numbers -- built-up is hidden at rung 0, where the
            # buildings themselves are drawn and a wash under them is a second
            # grey that adds nothing. The layer is still read (forest needs it),
            # so this is a drawing decision only.
            if rule.get("hidden", False):
                outlines[class_id] = 0
                outline_dashes[class_id] = 0
                outline_gaps[class_id] = 0
                tones[class_id] = "MapAreaTone::None"
                patterns[class_id] = "None"
                spacings[class_id] = 0
                continue
            outlines[class_id] = _round_px(rule.get("outline_width", 0), f"{what}.outline_width")
            # A dashed boundary. Both numbers or neither: a dash length with no
            # gap is a solid line the slow way, and a gap with no dash draws
            # nothing at all -- either would be a style that silently does not
            # do what it says.
            dash = _round_px(rule.get("outline_dash_px", 0), f"{what}.outline_dash_px")
            gap = _round_px(rule.get("outline_gap_px", 0), f"{what}.outline_gap_px")
            if (dash > 0) != (gap > 0):
                sys.exit(f"gen_mapstyle.py: {what}: outline_dash_px and outline_gap_px go together -- "
                         f"got {dash} and {gap}. A dash with no gap is a solid line, a gap with no dash "
                         f"draws nothing.")
            if dash > 0 and outlines[class_id] == 0:
                sys.exit(f"gen_mapstyle.py: {what}: a dashed outline needs outline_width above 0")
            outline_dashes[class_id] = dash
            outline_gaps[class_id] = gap
            tones[class_id] = _tone(rule, what)
            patterns[class_id], spacings[class_id] = _hatch(rule, what)
            if outlines[class_id] == 0 and tones[class_id] == "MapAreaTone::None" and patterns[class_id] == "None":
                sys.exit(f"gen_mapstyle.py: {what}: class '{name}' draws neither an outline, a tone nor a "
                         f"hatch. Drop the rule instead -- an enabled layer is read off the card in full.")
    if not any(outlines) and not any(t != "MapAreaTone::None" for t in tones) and not any(p != "None" for p in patterns):
        # Every class hidden at once. Not an error at a single rung -- a `when`
        # may legitimately empty the layer there -- but the caller (the layer's
        # `enabled`) is what decides whether the card is read, and that is not
        # per class. Report it off, which is exactly what gets drawn.
        return False, outlines, outline_dashes, outline_gaps, tones, patterns, spacings
    return True, outlines, outline_dashes, outline_gaps, tones, patterns, spacings


def place_dot_diameter(style):
    places = style.get("layers", {}).get("places")
    if places is None:
        sys.exit("gen_mapstyle.py: layers.places missing")
    if not places.get("enabled", True):
        print("gen_mapstyle.py: layers.places.enabled is false -- no place dots will be drawn")
        return 0
    diameter = 2 * _round_px(places.get("dot_radius_px", 0), "layers.places.dot_radius_px")
    if diameter > 255:
        sys.exit(f"gen_mapstyle.py: place dot diameter {diameter}px does not fit a uint8_t")
    return diameter


def points_style(style):
    """layers.points -> the eight C values for the POI marks.

    Absent block means the layer is off, so a style file written before the
    point layer existed keeps generating and simply draws no marks.
    """
    points = style.get("layers", {}).get("points")
    if points is None:
        print("gen_mapstyle.py: layers.points missing -- POI marks off")
        return False, False, 0, 0, 0, 0, 0, 0

    safety = bool(points.get("safety_enabled", True))
    landmark = bool(points.get("landmark_enabled", False))
    square = _round_px(points.get("square_px", 0), "layers.points.square_px")
    border = _round_px(points.get("border_px", 1), "layers.points.border_px")
    glyph = _round_px(points.get("glyph_px", 0), "layers.points.glyph_px")
    flag = _round_px(points.get("flag_px", 0), "layers.points.flag_px")
    # 0 disables clustering: every point draws its own mark, even two that
    # overlap. See docs/map-render-spec.md, "POI clustering" -- clustering
    # merges points that are close in SCREEN pixels, not on the ground, so
    # zooming in naturally pulls a merged mark apart with no per-zoom
    # tuning: the same two points are farther apart in screen px at a finer
    # mpp.
    cluster_radius = _round_px(points.get("cluster_radius_px", 0), "layers.points.cluster_radius_px")
    cluster_cell = _round_px(points.get("cluster_cell_px", 0), "layers.points.cluster_cell_px")

    if square and not (safety or landmark):
        sys.exit("gen_mapstyle.py: layers.points draws a square but both kinds are disabled. "
                 "Set square_px to 0 to hide the layer -- a hidden layer never opens a shard.")
    if square and glyph > square - 2:
        sys.exit(f"gen_mapstyle.py: layers.points.glyph_px {glyph} leaves no room inside a "
                 f"{square}px square (needs square_px - 2 at most, for the border and a pixel of air)")
    if square and flag > square // 2:
        sys.exit(f"gen_mapstyle.py: layers.points.flag_px {flag} is over half the {square}px square; "
                 "the corner flag would cover the glyph it is meant to qualify")
    if cluster_radius and not cluster_cell:
        sys.exit("gen_mapstyle.py: layers.points.cluster_radius_px is set but cluster_cell_px is not -- "
                 "a tile of more than one category needs a cell size to lay glyphs out in.")
    if cluster_cell and flag > cluster_cell // 2:
        sys.exit(f"gen_mapstyle.py: layers.points.flag_px {flag} is over half the "
                 f"cluster_cell_px {cluster_cell}; the corner flag would cover a tiled glyph")
    for name, value in (("square_px", square), ("border_px", border), ("glyph_px", glyph),
                        ("flag_px", flag), ("cluster_radius_px", cluster_radius),
                        ("cluster_cell_px", cluster_cell)):
        if value > 255:
            sys.exit(f"gen_mapstyle.py: layers.points.{name} {value}px does not fit a uint8_t")
    return safety, landmark, square, border, glyph, flag, cluster_radius, cluster_cell


def place_labels(style):
    """Everything layers.places says about labels, as one dict of C values.

    Two tiers keyed off the place rank the tile carries (city/town vs the rest,
    see docs/place-labels.md), plus the declutter numbers the placer needs.
    Disabled layer means no labels at all -- the renderer never opens the layer
    for drawing in that case anyway.
    """
    places = style.get("layers", {}).get("places") or {}
    enabled = places.get("enabled", True)
    out = {
        "px": _round_px(places.get("label_px", 0), "layers.places.label_px") if enabled else 0,
        "bold": bool(places.get("label_bold", True)),
        "minor_px": _round_px(places.get("label_minor_px", 0),
                              "layers.places.label_minor_px") if enabled else 0,
        "minor_bold": bool(places.get("label_minor_bold", False)),
        "offset": _round_px(places.get("label_offset_px", 0), "layers.places.label_offset_px"),
        "bg": bool(places.get("label_bg", False)),
        "bg_pad": _round_px(places.get("label_bg_pad_px", 0), "layers.places.label_bg_pad_px"),
        "bg_border": _round_px(places.get("label_bg_border_px", 0), "layers.places.label_bg_border_px"),
        "halo": _round_px(places.get("label_halo_px", 0), "layers.places.label_halo_px"),
        "max_labels": int(places.get("max_labels", 0)) if enabled else 0,
        # Absent means "the total", i.e. no extra restriction, so a style that
        # never mentions the tier caps behaves exactly as it did before they
        # existed. 0 is a real value and means none of that tier.
        "max_labels_major": int(places.get("max_labels_major", places.get("max_labels", 0))) if enabled else 0,
        "max_labels_minor": int(places.get("max_labels_minor", places.get("max_labels", 0))) if enabled else 0,
        "gap": _round_px(places.get("min_label_gap_px", 0), "layers.places.min_label_gap_px"),
        "route_overlap_pct": int(places.get("max_route_overlap_pct", 0)),
        "max_width": _round_px(places.get("label_max_width_px", 0), "layers.places.label_max_width_px"),
    }
    for name, value, ceiling in (("label_px", out["px"], 255),
                                 ("label_minor_px", out["minor_px"], 255),
                                 ("label_offset_px", out["offset"], 255),
                                 ("label_bg_pad_px", out["bg_pad"], 255),
                                 ("label_bg_border_px", out["bg_border"], 255),
                                 ("label_halo_px", out["halo"], 255),
                                 ("max_labels", out["max_labels"], 255),
                                 ("max_labels_major", out["max_labels_major"], 255),
                                 ("max_labels_minor", out["max_labels_minor"], 255),
                                 ("min_label_gap_px", out["gap"], 255),
                                 ("max_route_overlap_pct", out["route_overlap_pct"], 100),
                                 ("label_max_width_px", out["max_width"], 65535)):
        if value < 0 or value > ceiling:
            sys.exit(f"gen_mapstyle.py: layers.places.{name} {value} is outside 0..{ceiling}")
    if out["max_labels"] == 0 and (out["px"] or out["minor_px"]):
        print("gen_mapstyle.py: layers.places.max_labels is 0 -- label sizes are set but no label will be drawn")
    if out["max_labels_major"] == 0 and out["max_labels_minor"] == 0 and out["max_labels"] > 0:
        print("gen_mapstyle.py: both layers.places tier caps are 0 -- max_labels says labels are wanted "
              "but neither tier may draw one")
    # A halo behind a box is wasted work, and the renderer skips it (MapStyle.h).
    # Say so at generate time rather than leaving a style that reads as if it had
    # both.
    if out["bg"] and out["halo"]:
        print("gen_mapstyle.py: layers.places has both label_bg and label_halo_px -- the box wins, halo ignored")
    return out


def route(style):
    """(width, arrow_len, arrow_width) for layers.route, in device pixels.

    The route is told apart from the roads by width alone -- there is no colour
    on 1-bit e-ink -- so a width at or below the widest road is a style that
    hides the route inside the map. Warned about, not rejected: it is a legible
    thing to want while tuning, and the renderer honours whatever is here.
    """
    cfg = style.get("layers", {}).get("route")
    if cfg is None:
        sys.exit("gen_mapstyle.py: layers.route missing")
    if not cfg.get("enabled", True):
        print("gen_mapstyle.py: layers.route.enabled is false -- no route will be drawn")
        return 0, 0, 0
    width = _round_px(cfg.get("width", 0), "layers.route.width")
    arrow_len = _round_px(cfg.get("arrow_len_px", 0), "layers.route.arrow_len_px")
    arrow_width = _round_px(cfg.get("arrow_width_px", 0), "layers.route.arrow_width_px")
    for name, value in (("width", width), ("arrow_len_px", arrow_len),
                        ("arrow_width_px", arrow_width)):
        if value > 255:
            sys.exit(f"gen_mapstyle.py: layers.route.{name} {value}px does not fit a uint8_t")
    return width, arrow_len, arrow_width


def marker_anchor(style):
    device = style.get("device")
    if device is None:
        sys.exit("gen_mapstyle.py: device block missing")
    x = _round_px(device.get("marker_x_px", 0), "device.marker_x_px")
    y = _round_px(device.get("marker_y_px", 0), "device.marker_y_px")
    # Off-panel is allowed for tuning (MapViewport.h's marker ladder comment
    # says so), but it must still fit the int16_t it is stored in.
    if x > 32767 or y > 32767:
        sys.exit(f"gen_mapstyle.py: marker anchor {x},{y} does not fit an int16_t")
    return x, y


def _array(values, comments):
    """A C++ initialiser list, one value per line with its class name."""
    lines = ["    {"]
    for value, comment in zip(values, comments):
        lines.append(f"        {value},  // {comment}")
    lines.append("    },")
    return lines


def _style_literal(bundle):
    """One MapStyle's braced initialiser, as a list of lines.

    Designated initialisers on purpose: this file is generated, and a field
    reordered in MapStyle.h must break the build rather than silently shift a
    number into the wrong member (it did once, 2026-08-05).

    The text is also the dedup key -- two (mode, rung) pairs whose styles
    resolve identically share one entry in the emitted table, so a style with
    no `when` blocks at all costs one struct and a 21-byte index rather than
    21 structs.
    """
    (widths, casings, patterns, dashes, gaps, tones, buildings_px, water_px, landuse_px, dot_diameter,
     labels, points_px, route_px, marker_x, marker_y, puck_px) = bundle
    id_to_name = {class_id: name for name, class_id in _CLASS_ID.items()}
    lines = [
        "{",
        "    // Road width per MapClassId. 0 = not drawn.",
        "    .roadWidthPx =",
        "    {",
    ]
    for class_id in range(_CLASS_SLOTS):
        name = id_to_name.get(class_id, "(reserved)")
        lines.append(f"        {widths[class_id]},  // {class_id} {name}")
    lines += [
        "    },",
        "    // Casing per class, same indexing. 0 = solid black line.",
        "    .roadCasingPx =",
        "    {",
    ]
    for class_id in range(_CLASS_SLOTS):
        name = id_to_name.get(class_id, "(reserved)")
        lines.append(f"        {casings[class_id]},  // {class_id} {name}")
    lines += [
        "    },",
        "    // Line pattern per class. Order matters: designated initialisers",
        "    // must follow MapStyle.h.",
        "    .roadPattern =",
        "    {",
    ]
    for class_id in range(_CLASS_SLOTS):
        name = id_to_name.get(class_id, "(reserved)")
        lines.append(f"        MapLinePattern::{patterns[class_id]},  // {class_id} {name}")
    lines += [
        "    },",
        "    // Dash length per class, same indexing. 0 = a solid stroke.",
        "    .roadDashPx =",
        "    {",
    ]
    for class_id in range(_CLASS_SLOTS):
        name = id_to_name.get(class_id, "(reserved)")
        lines.append(f"        {dashes[class_id]},  // {class_id} {name}")
    lines += [
        "    },",
        "    .roadGapPx =",
        "    {",
    ]
    for class_id in range(_CLASS_SLOTS):
        name = id_to_name.get(class_id, "(reserved)")
        lines.append(f"        {gaps[class_id]},  // {class_id} {name}")
    lines += [
        "    },",
        "    // Dither tone for the inside of a cased road. None leaves it white.",
        "    .roadFillTone =",
        "    {",
    ]
    for class_id in range(_CLASS_SLOTS):
        name = id_to_name.get(class_id, "(reserved)")
        lines.append(f"        {tones[class_id]},  // {class_id} {name}")
    radius, ring, arrow = puck_px
    b_enabled, b_outline, b_tone, b_pattern, b_spacing = buildings_px
    (w_enabled, w_widths, w_outlines, w_patterns, w_dashes, w_gaps, w_tone, w_pattern, w_spacing,
     w_white) = water_px
    l_enabled, l_outlines, l_dashes, l_gaps, l_tones, l_patterns, l_spacings = landuse_px
    water_names = [name for name, _ in sorted(_WATER_CLASS.items(), key=lambda kv: kv[1])]
    landuse_names = ["(unused)", "forest", "built_up", "(unused)"]
    lines += [
        "    },",
        f"    .buildingsEnabled = {'true' if b_enabled else 'false'},",
        f"    .buildingOutlinePx = {b_outline},",
        f"    .buildingTone = {b_tone},",
        f"    .buildingHatch = MapAreaFill::Pattern::{b_pattern},",
        f"    .buildingHatchSpacingPx = {b_spacing},",
        f"    .waterEnabled = {'true' if w_enabled else 'false'},",
        "    .waterLinePx =",
        *_array(w_widths, water_names),
        "    .waterOutlinePx =",
        *_array(w_outlines, water_names),
        "    .waterPattern =",
        *_array([f"MapLinePattern::{p}" for p in w_patterns], water_names),
        "    .waterDashPx =",
        *_array(w_dashes, water_names),
        "    .waterGapPx =",
        *_array(w_gaps, water_names),
        f"    .waterTone = {w_tone},",
        f"    .waterHatch = MapAreaFill::Pattern::{w_pattern},",
        f"    .waterHatchSpacingPx = {w_spacing},",
        f"    .waterHatchWhite = {'true' if w_white else 'false'},",
        f"    .landuseEnabled = {'true' if l_enabled else 'false'},",
        "    .landuseOutlinePx =",
        *_array(l_outlines, landuse_names),
        "    .landuseTone =",
        *_array(l_tones, landuse_names),
        "    .landuseHatch =",
        *_array([f"MapAreaFill::Pattern::{p}" for p in l_patterns], landuse_names),
        "    .landuseHatchSpacingPx =",
        *_array(l_spacings, landuse_names),
        "    .landuseOutlineDashPx =",
        *_array(l_dashes, landuse_names),
        "    .landuseOutlineGapPx =",
        *_array(l_gaps, landuse_names),
        f"    .placeDotDiameterPx = {dot_diameter},",
        f"    .placeLabelPx = {labels['px']},",
        f"    .placeLabelBold = {'true' if labels['bold'] else 'false'},",
        f"    .placeLabelMinorPx = {labels['minor_px']},",
        f"    .placeLabelMinorBold = {'true' if labels['minor_bold'] else 'false'},",
        f"    .placeLabelOffsetPx = {labels['offset']},",
        f"    .placeLabelBg = {'true' if labels['bg'] else 'false'},",
        f"    .placeLabelBgPadPx = {labels['bg_pad']},",
        f"    .placeLabelBgBorderPx = {labels['bg_border']},",
        f"    .placeLabelHaloPx = {labels['halo']},",
        f"    .placeMaxLabels = {labels['max_labels']},",
        f"    .placeMaxLabelsMajor = {labels['max_labels_major']},",
        f"    .placeMaxLabelsMinor = {labels['max_labels_minor']},",
        f"    .placeLabelGapPx = {labels['gap']},",
        f"    .placeLabelRouteOverlapPct = {labels['route_overlap_pct']},",
        f"    .placeLabelMaxWidthPx = {labels['max_width']},",
        f"    .pointsSafetyEnabled = {'true' if points_px[0] else 'false'},",
        f"    .pointsLandmarkEnabled = {'true' if points_px[1] else 'false'},",
        f"    .pointSquarePx = {points_px[2]},",
        f"    .pointBorderPx = {points_px[3]},",
        f"    .pointGlyphPx = {points_px[4]},",
        f"    .pointFlagPx = {points_px[5]},",
        f"    .pointClusterRadiusPx = {points_px[6]},",
        f"    .pointClusterCellPx = {points_px[7]},",
        f"    .routeWidthPx = {route_px[0]},",
        f"    .routeArrowLenPx = {route_px[1]},",
        f"    .routeArrowWidthPx = {route_px[2]},",
        f"    .markerXPx = {marker_x},",
        f"    .markerYPx = {marker_y},",
        f"    .puckRadiusPx = {radius},",
        f"    .puckRingPx = {ring},",
        f"    .puckArrowPx = {arrow},",
        "}",
    ]
    return lines


def compile_style(style):
    """Every number MapStyle holds, for one already-resolved style dict.

    Takes a style with no `when` left in it (mapstyle_variants.resolve), so
    every validation below runs per variant: a rung that hides a class the
    hard way, or patches a width past 255, fails the build at that rung and
    names it.
    """
    widths, casings, patterns, dashes, gaps, tones = road_widths(style)
    return (widths, casings, patterns, dashes, gaps, tones,
            buildings(style), water(style), landuse(style), place_dot_diameter(style),
            place_labels(style), points_style(style), route(style),
            *marker_anchor(style), puck(style))


def _print_summary(bundle, what):
    (widths, casings, _patterns, _dashes, _gaps, _tones, buildings_px, water_px, landuse_px, dot_diameter,
     labels, points_px, route_px, marker_x, marker_y, puck_px) = bundle
    drawn = sum(1 for w in widths if w)
    cased = sum(1 for c in casings if c)
    print(f"gen_mapstyle.py: {what}: {drawn} road classes drawn, widths {min(w for w in widths if w)}"
          f"..{max(widths)}px, {cased} cased, place dot {dot_diameter}px, marker {marker_x},{marker_y}, "
          f"puck r{puck_px[0]}/ring{puck_px[1]}/arrow{puck_px[2]}")
    print(f"gen_mapstyle.py: {what}: POI marks {'safety' if points_px[0] else '-'}"
          f"{'+landmark' if points_px[1] else ''} square {points_px[2]}px, glyph {points_px[4]}px, "
          f"flag {points_px[5]}px, cluster radius {points_px[6]}px cell {points_px[7]}px")
    print(f"gen_mapstyle.py: {what}: buildings {'on' if buildings_px[0] else 'off'} "
          f"(outline {buildings_px[1]}px, tone {_toneLabel(buildings_px[2])}, hatch {buildings_px[3]}/{buildings_px[4]}px), "
          f"water {'on' if water_px[0] else 'off'} "
          f"(widths {water_px[1]}, outlines {water_px[2]}, dashes {water_px[4]}/{water_px[5]}, "
          f"tone {_toneLabel(water_px[6])}, "
          f"hatch {water_px[7]}/{water_px[8]}px{' white' if water_px[9] else ''})")
    widest_road = max(widths)
    if route_px[0] and route_px[0] <= widest_road:
        print(f"gen_mapstyle.py: warning -- {what}: route width {route_px[0]}px is not wider than the "
              f"widest road ({widest_road}px); width is the only thing telling them apart on 1-bit e-ink")
    print(f"gen_mapstyle.py: {what}: route {route_px[0]}px wide, arrow {route_px[1]}x{route_px[2]}px")
    knockout = "box" if labels["bg"] else "halo {}px".format(labels["halo"])
    print(f"gen_mapstyle.py: {what}: place labels {labels['px']}px{' bold' if labels['bold'] else ''} major / "
          f"{labels['minor_px']}px{' bold' if labels['minor_bold'] else ''} minor, max {labels['max_labels']} ({labels['max_labels_major']} major / {labels['max_labels_minor']} minor), "
          f"{knockout}, gap {labels['gap']}px, "
          f"route overlap <= {labels['route_overlap_pct']}%, width cap {labels['max_width']}px")
    if landuse_px[0]:
        print(f"gen_mapstyle.py: {what}: landuse on -- forest tone {_toneLabel(landuse_px[4][1])}/hatch {landuse_px[5][1]}, "
              f"built_up tone {_toneLabel(landuse_px[4][2])}/hatch {landuse_px[5][2]}")
    else:
        print(f"gen_mapstyle.py: {what}: landuse off")


def _indent(lines, spaces):
    pad = " " * spaces
    return [pad + line if line else line for line in lines]


def gen_cpp(base_bundle, variants, index):
    """The whole generated header: the base style, the variant table, the index.

    `variants` is the deduplicated list of resolved styles, `index[mode][step]`
    the slot each (mode, rung) pair uses. The device does one array lookup --
    every rule in mapstyle.json was already evaluated here.
    """
    lines = [
        "#pragma once",
        "",
        f"// {_HEADER_NOTE}",
        "",
        '#include "MapRideMode.h"',
        '#include "MapStyle.h"',
        "",
        "// The style before any mode or rung has its say. This is what an",
        "// invariant is read off -- MapViewport's marker anchor is a constexpr",
        "// built on it, and `when` is banned under `device` for exactly that",
        "// reason (scripts/mapstyle_variants.py).",
        "inline constexpr MapStyle kDefaultMapStyle =",
    ]
    lines += _indent(_style_literal(base_bundle), 4)
    lines[-1] = lines[-1] + ";"
    lines += [
        "",
        "// One entry per style that actually differs. Two (mode, rung) pairs whose",
        "// resolved styles are identical share a slot, so a mapstyle.json with no",
        "// `when` blocks compiles to exactly one struct here.",
        f"inline constexpr MapStyle kMapStyleVariants[{len(variants)}] = {{",
    ]
    for slot, (bundle, users) in enumerate(variants):
        who = ", ".join(f"{mode}@{step}" for mode, step in users)
        lines.append(f"    // [{slot}] {who}")
        body = _indent(_style_literal(bundle), 4)
        body[-1] = body[-1] + ","
        lines += body
    lines += [
        "};",
        "",
        "// kMapStyleIndex[mode][rung] -- MapRideMode order (Ride, Hike, Cycle),",
        "// MapViewport's zoom ladder order. mapStyleFor() in MapStyleTable.h is the",
        "// only thing that should read this.",
        f"inline constexpr uint8_t kMapStyleIndex[kMapRideModeCount][kMapZoomStepCount] = {{",
    ]
    for mode_id, mode_name in enumerate(mapstyle_variants.MODE_ORDER):
        row = ", ".join(str(index[mode_id][step]) for step in range(mapstyle_variants.ZOOM_STEPS))
        lines.append(f"    {{{row}}},  // {mode_name}")
    lines += ["};", ""]
    return "\n".join(lines)


def main(repo_root, style_path=None, output_path=None):
    if style_path is None:
        style_path = os.path.join(repo_root, "data", "mapstyle.json")
    if output_path is None:
        output_path = os.path.join(repo_root, "src", "activities", "map", "MapStyleDefaults.h")

    _load_variants(repo_root)

    if not os.path.isfile(style_path):
        sys.exit(f"gen_mapstyle.py: {style_path} not found")

    with open(style_path) as f:
        style = json.load(f)

    try:
        base_style = mapstyle_variants.base(style)
    except mapstyle_variants.VariantError as error:
        sys.exit(f"gen_mapstyle.py: {error}")
    base_bundle = compile_style(base_style)
    _print_summary(base_bundle, "base")

    # Resolve every (mode, rung) pair and deduplicate by the generated text.
    # The dedup is what keeps this cheap: a style with no variants at all is
    # one struct, and a style that varies only the road widths at the coarse
    # rungs is a handful.
    variants = []
    by_text = {}
    index = [[0] * mapstyle_variants.ZOOM_STEPS for _ in mapstyle_variants.MODE_ORDER]
    for mode_id, mode_name in enumerate(mapstyle_variants.MODE_ORDER):
        for step in range(mapstyle_variants.ZOOM_STEPS):
            try:
                resolved = mapstyle_variants.resolve(style, mode_name, step)
            except mapstyle_variants.VariantError as error:
                sys.exit(f"gen_mapstyle.py: {mode_name}@{step}: {error}")
            bundle = compile_style(resolved)
            text = "\n".join(_style_literal(bundle))
            slot = by_text.get(text)
            if slot is None:
                slot = len(variants)
                by_text[text] = slot
                variants.append((bundle, []))
            variants[slot][1].append((mode_name, step))
            index[mode_id][step] = slot

    # The marker anchor must be the same everywhere: MapViewport turns it into
    # a constexpr and the tile arithmetic is built on it. `when` is banned under
    # `device`, so this can only trip on a hand-edited generator -- it is here
    # because the failure would otherwise be a viewport that disagrees with
    # itself at one rung, which is very hard to see on a panel.
    for bundle, users in variants:
        if (bundle[12], bundle[13]) != (base_bundle[12], base_bundle[13]):
            sys.exit(f"gen_mapstyle.py: {users[0][0]}@{users[0][1]}: marker anchor differs from the base "
                     f"style -- the viewport anchor cannot vary by mode or rung")

    print(f"gen_mapstyle.py: {len(variants)} distinct style(s) across "
          f"{len(mapstyle_variants.MODE_ORDER)} modes x {mapstyle_variants.ZOOM_STEPS} rungs")
    if len(variants) > 1:
        for slot, (bundle, users) in enumerate(variants):
            _print_summary(bundle, f"[{slot}] {users[0][0]}@{users[0][1]}")

    with open(output_path, "w") as f:
        f.write(gen_cpp(base_bundle, variants, index))
    print(f"gen_mapstyle.py: wrote {output_path}")


# PlatformIO/SCons entry point -- Import and env are SCons builtins injected at
# runtime. `__file__` is not defined in that exec environment (the same trap
# git_branch.py and gen_mode_masks.py avoid the same way), so the repo root has
# to come from env rather than from this file's own path.
if __name__ == "__main__":
    _repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(_repo_root, *sys.argv[1:3])
else:
    try:
        Import("env")  # noqa: F821
        main(env["PROJECT_DIR"])  # noqa: F821
    except NameError:
        pass
