#pragma once

#include <Icon.h>

#include <cstdint>

// Generated by scripts/gen_map_header_icons.py. Do not edit.
// 14px, drawn with GfxRenderer::drawMono1bpp() (not drawIcon() --
// see the script's own header comment for why).

// transferBle  (lucide: arrow-left-right)
static const uint8_t icon_transferBle_bits[] = {0xFF, 0xFF, 0xF7, 0xFF, 0xE7, 0xFF, 0xCF, 0xFF, 0xC0, 0x0F,
                                                0xE7, 0xFF, 0xF7, 0xFF, 0xFF, 0xBF, 0xFF, 0x9F, 0xC0, 0x0F,
                                                0xFF, 0xCF, 0xFF, 0x9F, 0xFF, 0xBF, 0xFF, 0xFF};
static const freeink::Icon icon_transferBle = {14, 14, 6, icon_transferBle_bits};
