#pragma once

#include "Icon.h"

// Generated by freeink-sdk/libs/assets/Icons/tools/gen_icons.py from Lucide
// mountain.svg. Do not edit.
//
// Rasterised with cairosvg, not gen_icons.py's own rsvg-convert -- this
// machine has librsvg2 (the library) but not librsvg2-bin (the rsvg-convert
// binary the script shells out to). gen_pin_icons.py's own docstring already
// notes the two rasterisers "agree closely enough at these sizes"; not
// independently re-verified here, at 16px.
// Sizes: 16px. Icons: 1.

// mountain  (lucide: mountain)
static const uint8_t icon_mountain_16_bits[] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFB, 0xFF, 0xF1, 0xFF, 0xF5, 0xCF, 0xF4,
                                                0x8F, 0xEE, 0x37, 0xEE, 0x77, 0xEF, 0xF7, 0xDF, 0xFB, 0xDF, 0xFB,
                                                0xDF, 0xFB, 0xBF, 0xFD, 0x80, 0x01, 0x80, 0x01, 0xFF, 0xFF};
static const freeink::Icon icon_mountain_16 = {16, 16, 10, icon_mountain_16_bits};
