#pragma once

// Generated by gen_class_enum.py from class_spec.py. Do not hand-edit.
// Little-endian on the wire, no byte swapping -- see docs/map-data-spec.md.

#include <cstdint>

static constexpr uint16_t kClassEnumVersion = 1;
static constexpr uint8_t kClassEnumSlots = 32;

enum class MapClassId : uint8_t {
  Unknown = 0,
  Motorway = 1,
  Trunk = 2,
  Primary = 3,
  Secondary = 4,
  Tertiary = 5,
  Unclassified = 6,
  Residential = 7,
  LivingStreet = 8,
  Service = 9,
  Pedestrian = 10,
  Track = 11,
  Bridleway = 12,
  Cycleway = 13,
  Footway = 14,
  Path = 15,
  Steps = 16,
  Construction = 17,
  Ferry = 18,
  Railway = 19,
  Aerialway = 20,
};

// Wire name per class_id, indexed by the id itself. Reserved slots are
// nullptr, so a name lookup can never resolve one -- that is what makes
// mapstyle.json's mode class lists safe to parse against this table.
static constexpr const char* kMapClassNames[32] = {
    "unknown",       "motorway",     "trunk",      "primary", "secondary", "tertiary", "unclassified", "residential",
    "living_street", "service",      "pedestrian", "track",   "bridleway", "cycleway", "footway",      "path",
    "steps",         "construction", "ferry",      "railway", "aerialway", nullptr,    nullptr,        nullptr,
    nullptr,         nullptr,        nullptr,      nullptr,   nullptr,     nullptr,    nullptr,        nullptr,
};

static constexpr int kFlagFieldBits = 16;

enum MapWayFlag : uint16_t {
  kFlagLink = 1u << 0,
  kFlagBridge = 1u << 1,
  kFlagTunnel = 1u << 2,
  kFlagOneway = 1u << 3,
  kFlagUnpaved = 1u << 4,
  kFlagNoMotor = 1u << 5,
  kFlagNoBicycle = 1u << 6,
  kFlagNoFoot = 1u << 7,
};
