#pragma once

// Generated by gen_mode_masks.py from style.json's `modes` block and class_spec.py. Do not hand-edit.

#include <cstdint>

inline constexpr uint32_t kDefaultRideMask = 0x00040bffu;
inline constexpr uint32_t kDefaultHikeMask = 0x001dffffu;
inline constexpr uint32_t kDefaultCycleMask = 0x000cabffu;
