#pragma once

#include <cstdint>
#include <string_view>

#include "MapClassEnum.h"
#include "MapModeMaskDefaults.h"
#include "MapRideMode.h"

// The render-time mode filter -- docs/map-data-spec.md, "Mode is a
// render-time filter".
//
// One tile set serves ride, hike and cycle. A mode is a 32-bit mask over the
// tile format's own class_id enum, and a way is drawn when
// `mask & (1u << class_id)`. Nothing is filtered at build time: doing that
// would mean three tile sets on the card and a re-sync every time the rider
// changes mode.
//
// Pure. No I/O, no Arduino, no JSON, no card. The masks are compiled
// constants (MapModeMaskDefaults.h) -- nothing loads or overrides them at
// runtime, which is what lets the mask logic be tested natively with no
// filesystem in the loop at all.

// One class's bit. Written as a function rather than a macro so a bad
// argument is a compile error. Kept for callers that build or test a mask
// against a named class (MapTileReaderGoldenTest.cpp); the compiled mode
// masks below no longer need it, since gen_mode_masks.py emits their bits
// directly.
constexpr uint32_t mapClassBit(MapClassId id) { return 1u << static_cast<uint8_t>(id); }

// kDefaultRideMask / kDefaultHikeMask / kDefaultCycleMask come from
// MapModeMaskDefaults.h, generated by mapbuilder/gen_mode_masks.py from
// style.json's `modes` block. The style is a build-time input -- the device
// reads no style file at runtime -- so these are the only copy, not a
// fallback the style overrides. See docs/map-render-spec.md, "Where the app
// gets the style".
//
// Ride keeps `track`: this is a trail device, and a forest track is the point
// of it rather than an edge case. What a track is *closed* to is the
// `no_motor` flag's job, not the class list's -- see docs/map-data-spec.md,
// "The class enum".

// One mask per mode, indexed by MapRideMode. Default-constructed to the
// compiled masks above, so an instance is usable with no loading step at all.
// One mask per (mode, zoom rung), indexed by MapRideMode and the zoom ladder
// step. Default-constructed to the compiled table, so an instance is usable
// with no loading step at all.
//
// The rung is in here because a class filter that ignores zoom draws a
// footpath at 45 m/px, where it is one pixel of noise, and drops nothing at
// all at 1 m/px, where it is the thing being walked. gen_mode_masks.py builds
// each entry as "the mode's classes AND the classes that rung's style draws",
// so the filter can never let through a way the style then hides
// (docs/map-data-spec.md, "Style is per mode and per rung").
struct MapModeMasks {
  uint32_t mask[kMapRideModeCount][kMapZoomStepCount] = {
      {kMapModeMasks[0][0], kMapModeMasks[0][1], kMapModeMasks[0][2], kMapModeMasks[0][3],
       kMapModeMasks[0][4], kMapModeMasks[0][5], kMapModeMasks[0][6]},
      {kMapModeMasks[1][0], kMapModeMasks[1][1], kMapModeMasks[1][2], kMapModeMasks[1][3],
       kMapModeMasks[1][4], kMapModeMasks[1][5], kMapModeMasks[1][6]},
      {kMapModeMasks[2][0], kMapModeMasks[2][1], kMapModeMasks[2][2], kMapModeMasks[2][3],
       kMapModeMasks[2][4], kMapModeMasks[2][5], kMapModeMasks[2][6]},
  };

  // Out-of-range arguments clamp rather than fault: the rung comes from
  // settings and the mode from a BLE or serial command, and neither may index
  // past the array (../../../CLAUDE.md, "Security").
  uint32_t forMode(MapRideMode mode, int zoomStep) const {
    const uint8_t index = static_cast<uint8_t>(mode) < kMapRideModeCount ? static_cast<uint8_t>(mode) : 0;
    const int step = zoomStep < 0 ? 0 : (zoomStep >= kMapZoomStepCount ? kMapZoomStepCount - 1 : zoomStep);
    return mask[index][step];
  }
};

// Resolves one of the tile format's class names ("motorway", "living_street")
// to its class_id. Reserved slots are nullptr in kMapClassNames and so can
// never be resolved by name -- an unknown name is a false return, never a
// silently wrong bit.
bool mapClassIdFromName(std::string_view name, uint8_t& outId);

// mapstyle.json's `modes` keys. Returns false for anything else.
bool mapRideModeFromName(std::string_view name, MapRideMode& outMode);
