#pragma once

// Generated by gen_point_enum.py from point_spec.py. Do not hand-edit.
// The point file's kind, category and reliability bytes. Little-endian on the
// wire, no byte swapping -- docs/point-file-spec.md.

#include <cstdint>

static constexpr uint16_t kPointSpecVersion = 1;
static constexpr uint8_t kPointNameMaxBytes = 63;

enum class MapPointKind : uint8_t {
  Unknown = 0,
  Safety = 1,
  Landmark = 2,
};

// Safety categories, in the fixed row order of the Nearby menu.
enum class MapSafetyCategory : uint8_t {
  Unknown = 0,
  Water = 1,
  Shelter = 2,
  Hut = 3,
  Lodging = 4,
  Fuel = 5,
  Hospital = 6,
  Pharmacy = 7,
  Rescue = 8,
  EmergencyPhone = 9,
  Transport = 10,
};

static constexpr uint8_t kSafetyCategoryCount = 11;

// Wire name per category id, indexed by the id. Never a UI string: the
// menu labels are the firmware's own, translated, and longer than these.
static constexpr const char* kSafetyCategoryNames[11] = {
    "unknown",  "water",  "shelter",         "hut",       "lodging", "fuel", "hospital",
    "pharmacy", "rescue", "emergency_phone", "transport",
};

enum MapPointFlag : uint8_t {
  kPointUnverified = 1u << 0,
  kPointRestricted = 1u << 1,
  kPointSeasonal = 1u << 2,
  kPointFee = 1u << 3,
  kPointNotPotable = 1u << 4,
  kPointUnstaffed = 1u << 5,
  kPointOpenSided = 1u << 6,
};

// Any of these set draws the one corner flag on the square. not_potable is
// deliberately absent: such a point is filtered out of water entirely by the
// writer, so a reader must never see it under that category.
static constexpr uint8_t kPointFlaggedOnMapMask = 0x0f;
