#pragma once

// Generated by gen_waymark_enum.py from waymark_spec.py. Do not hand-edit.
// The waymark symbol id in a way record's flags 8-13 -- six bits, 64 values,
// three sentinels and 61 colour+shape pairs. docs/map-data-spec.md, "The
// waymark symbol id, and why it is a symbol rather than a colour".
//
// The device only ever reads a number. These names exist so a style's glyph
// table can be written against something legible, and so the collapse from 61
// ids down to the dozen glyphs a 11 px panel can distinguish can be
// collision-aware: two ids that never co-occur in one region may share a glyph,
// the way two countries can share a flag design.

#include <cstdint>

static constexpr uint16_t kWaymarkTableVersion = 1;
static constexpr uint8_t kWaymarkIdSlots = 64;

// The bits themselves, so nothing has to hard-code the shift.
static constexpr uint8_t kMapWaymarkShift = 8;
static constexpr uint16_t kMapWaymarkMask = 0x3F00;

static constexpr uint8_t mapWaymarkId(uint16_t flags) {
  return static_cast<uint8_t>((flags & kMapWaymarkMask) >> kMapWaymarkShift);
}

// Not a member of any waymarked route relation.
static constexpr uint8_t kWaymarkNotWaymarked = 0;
// On a waymarked route, and nothing is known about how the waymark looks.
// The correct rendering is a plain emphasised trail line, not a question mark:
// this is what the whole of North America resolves to, because the ways there
// carry no `osmc:symbol` at all.
//
// **Norway does not land here.** The DNT mark is `red:white:::T:red`, which
// resolves through the text clause to the pair (red, "T"); that pair is not one
// of the 61 the table holds, so Norway lands on kWaymarkOffTable (63). Every
// Jotunheimen relation measured for docs/map-data-spec.md carries exactly that
// value. Anyone designing the glyph collapse must count Norway in the off-table
// bucket, not in this one.
static constexpr uint8_t kWaymarkRouteNoSymbol = 1;
static constexpr uint8_t kWaymarkPairMin = 2;
static constexpr uint8_t kWaymarkPairMax = 62;
// A real pattern the table does not hold. Distinct from kWaymarkRouteNoSymbol:
// no pattern is not a pattern.
static constexpr uint8_t kWaymarkOffTable = 63;

enum class MapWaymarkColour : uint8_t {
  Black = 0,
  Blue = 1,
  Brown = 2,
  Gray = 3,
  Green = 4,
  Orange = 5,
  Purple = 6,
  Red = 7,
  White = 8,
  Yellow = 9,
  None = 0xFF,  // the three sentinels have no colour
};

// clang-format off
static constexpr const char* kMapWaymarkNames[64] = {
  "not_waymarked",     // 0
  "route_no_symbol",   // 1
  "yellow_diamond",    // 2
  "white_stripe",      // 3
  "yellow_bar",        // 4
  "yellow_pointer",    // 5
  "red_bar",           // 6
  "white_bar",         // 7
  "red_lower",         // 8
  "blue_bar",          // 9
  "green_bar",         // 10
  "red_arrow",         // 11
  "yellow_upper",      // 12
  "yellow_circle",     // 13
  "blue_diamond",      // 14
  "black_rectangle",   // 15
  "yellow_lower",      // 16
  "white_arrow",       // 17
  "red_dot",           // 18
  "yellow_arrow",      // 19
  "blue_dot",          // 20
  "white_dot",         // 21
  "blue_none",         // 22
  "red_diamond",       // 23
  "yellow_dot",        // 24
  "blue_arrow",        // 25
  "green_backslash",   // 26
  "blue_stripe",       // 27
  "red_cross",         // 28
  "green_lower",       // 29
  "blue_upper",        // 30
  "red_circle",        // 31
  "red_triangle",      // 32
  "yellow_round",      // 33
  "green_dot",         // 34
  "blue_cross",        // 35
  "red_stripe",        // 36
  "yellow_none",       // 37
  "white_upper",       // 38
  "yellow_triangle",   // 39
  "yellow_rectangle",  // 40
  "blue_pointer",      // 41
  "red_round",         // 42
  "brown_arrow",       // 43
  "red_rectangle",     // 44
  "white_circle",      // 45
  "red_none",          // 46
  "blue_triangle",     // 47
  "green_circle",      // 48
  "green_triangle",    // 49
  "yellow_stripe",     // 50
  "green_stripe",      // 51
  "blue_circle",       // 52
  "black_bar",         // 53
  "blue_rectangle",    // 54
  "green_arrow",       // 55
  "green_rectangle",   // 56
  "green_diamond",     // 57
  "white_lower",       // 58
  "blue_lower",        // 59
  "yellow_cross",      // 60
  "black_stripe",      // 61
  "green_none",        // 62
  "off_table",         // 63
};
// clang-format on

// Colour per id, so a style can group by colour without parsing a name.
// A sentinel is MapWaymarkColour::None.
// clang-format off
static constexpr MapWaymarkColour kMapWaymarkColours[64] = {
  MapWaymarkColour::None,
  MapWaymarkColour::None,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::White,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Red,
  MapWaymarkColour::White,
  MapWaymarkColour::Red,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Green,
  MapWaymarkColour::Red,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Black,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::White,
  MapWaymarkColour::Red,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Blue,
  MapWaymarkColour::White,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Red,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Green,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Red,
  MapWaymarkColour::Green,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Red,
  MapWaymarkColour::Red,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Green,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Red,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::White,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Red,
  MapWaymarkColour::Brown,
  MapWaymarkColour::Red,
  MapWaymarkColour::White,
  MapWaymarkColour::Red,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Green,
  MapWaymarkColour::Green,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Green,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Black,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Green,
  MapWaymarkColour::Green,
  MapWaymarkColour::Green,
  MapWaymarkColour::White,
  MapWaymarkColour::Blue,
  MapWaymarkColour::Yellow,
  MapWaymarkColour::Black,
  MapWaymarkColour::Green,
  MapWaymarkColour::None,
};
// clang-format on

// Shape per id, verbatim from `osmc:symbol`'s foreground. "none" is a real
// shape -- a plain coloured line with no mark on it -- and is not a sentinel.
// clang-format off
static constexpr const char* kMapWaymarkShapes[64] = {
  nullptr,
  nullptr,
  "diamond",
  "stripe",
  "bar",
  "pointer",
  "bar",
  "bar",
  "lower",
  "bar",
  "bar",
  "arrow",
  "upper",
  "circle",
  "diamond",
  "rectangle",
  "lower",
  "arrow",
  "dot",
  "arrow",
  "dot",
  "dot",
  "none",
  "diamond",
  "dot",
  "arrow",
  "backslash",
  "stripe",
  "cross",
  "lower",
  "upper",
  "circle",
  "triangle",
  "round",
  "dot",
  "cross",
  "stripe",
  "none",
  "upper",
  "triangle",
  "rectangle",
  "pointer",
  "round",
  "arrow",
  "rectangle",
  "circle",
  "none",
  "triangle",
  "circle",
  "triangle",
  "stripe",
  "stripe",
  "circle",
  "bar",
  "rectangle",
  "arrow",
  "rectangle",
  "diamond",
  "lower",
  "lower",
  "cross",
  "stripe",
  "none",
  nullptr,
};
// clang-format on

//
// Nothing in src/ or lib/ includes this header, so a regeneration across
// the repo boundary could drift the bit layout and no build would notice.
// These asserts are that check, and test/map_flag_rules/MapFlagRulesTest.cpp
static_assert(kMapWaymarkShift == 8, "the waymark id starts at flags bit 8");
static_assert(kMapWaymarkMask == 0x3F00, "six bits, 8 through 13");
static_assert((kMapWaymarkMask >> kMapWaymarkShift) == kWaymarkIdSlots - 1, "the mask must cover all 64 ids");
static_assert((kMapWaymarkMask & 0xC000u) == 0, "bits 14-15 are seasonal and permit (scripts/gen_mapstyle.py:218-219)");
static_assert((kMapWaymarkMask & 0x00FFu) == 0, "bits 0-7 are the named way flags (scripts/gen_mapstyle.py:210-217)");
static_assert(kWaymarkNotWaymarked == 0, "sentinel");
static_assert(kWaymarkRouteNoSymbol == 1, "sentinel");
static_assert(kWaymarkOffTable == kWaymarkIdSlots - 1, "sentinel, the top of the range");
static_assert(kWaymarkPairMin == kWaymarkRouteNoSymbol + 1, "the pairs start above the low sentinels");
static_assert(kWaymarkPairMax == kWaymarkOffTable - 1, "the pairs stop below the high sentinel");
static_assert(kWaymarkPairMax - kWaymarkPairMin + 1 == 61, "61 colour+shape pairs");
static_assert(mapWaymarkId(0x0000) == kWaymarkNotWaymarked, "an unflagged way is not waymarked");
static_assert(mapWaymarkId(0xFFFF) == kWaymarkOffTable, "all bits set reads as the top id, not as an overflow");
static_assert(mapWaymarkId(0x0100) == 1, "bit 8 alone is id 1");
static_assert(mapWaymarkId(0xC0FF) == kWaymarkNotWaymarked, "the other flag bits must not leak into the id");


// The three tables are parallel, one row per id, and a regeneration that drops
// or adds a row is the drift these catch. Compiled by
// test/map_flag_rules/MapFlagRulesTest.cpp, same as the bit asserts above.
static_assert(sizeof(kMapWaymarkNames) / sizeof(kMapWaymarkNames[0]) == kWaymarkIdSlots, "one name per id");
static_assert(sizeof(kMapWaymarkColours) / sizeof(kMapWaymarkColours[0]) == kWaymarkIdSlots, "one colour per id");
static_assert(sizeof(kMapWaymarkShapes) / sizeof(kMapWaymarkShapes[0]) == kWaymarkIdSlots, "one shape per id");
static_assert(kMapWaymarkColours[kWaymarkNotWaymarked] == MapWaymarkColour::None, "a sentinel has no colour");
static_assert(kMapWaymarkColours[kWaymarkRouteNoSymbol] == MapWaymarkColour::None, "a sentinel has no colour");
static_assert(kMapWaymarkColours[kWaymarkOffTable] == MapWaymarkColour::None, "a sentinel has no colour");
static_assert(kMapWaymarkShapes[kWaymarkNotWaymarked] == nullptr, "a sentinel has no shape");
static_assert(kMapWaymarkShapes[kWaymarkRouteNoSymbol] == nullptr, "a sentinel has no shape");
static_assert(kMapWaymarkShapes[kWaymarkOffTable] == nullptr, "a sentinel has no shape");
static_assert(kMapWaymarkColours[kWaymarkPairMin] != MapWaymarkColour::None, "a pair carries a colour");
static_assert(kMapWaymarkColours[kWaymarkPairMax] != MapWaymarkColour::None, "a pair carries a colour");
static_assert(kMapWaymarkShapes[kWaymarkPairMin] != nullptr, "a pair carries a shape");
static_assert(kMapWaymarkShapes[kWaymarkPairMax] != nullptr, "a pair carries a shape");