#pragma once

#include <Icon.h>

#include <cstdint>

#include "PinCatalog.h"
#include "components/icons/pins_shape.h"

// Which baked bitmap a pin type is drawn with.
//
// The pin's *shape* is a separate table (kPinShapeFrames, one frame per rotation);
// this is only what goes inside its head. The two are apart on purpose: the shape
// turns so its point can aim at where the pin actually is, and a numeral or a P
// must not turn with it (MapActivity::drawPinBalloon()).
//
// Generated by scripts/gen_pin_icons.py from src/components/icons/pins.icons.txt.
//
// `#1`-`#5` carry their own numeral rather than sharing one glyph -- a 3 is the
// clearest possible way to say "#3", and Lucide has no numerals, so the generator
// bakes those from a font (src/components/icons/pins.icons.txt).
//
// A key this build does not know falls back to `#1`'s numeral. Wrong-but-visible
// beats absent: a pin written by a later firmware must still be findable and
// deletable (PinCatalog.h, the unknown-key rule).
inline const uint8_t* pinGlyphBits(size_t catalogIndex) {
  switch (catalogIndex) {
    case 0:
      return kPinGlyphPinBaseBits;
    case 1:
      return kPinGlyphPinParkingBits;
    case 2:
      return kPinGlyphPinDestBits;
    case 3:
      return kPinGlyphPinMeetBits;
    case 4:
      return kPinGlyphPinCampBits;
    case 5:
      return kPinGlyphPinFavoriteBits;
    case 6:
      return kPinGlyphPinC1Bits;
    case 7:
      return kPinGlyphPinC2Bits;
    case 8:
      return kPinGlyphPinC3Bits;
    case 9:
      return kPinGlyphPinC4Bits;
    case 10:
      return kPinGlyphPinC5Bits;
    default:
      return kPinGlyphPinC1Bits;
  }
}

// The same glyph, wrapped as a freeink::Icon, for a picker that wants to show
// a pin type's own mark rather than a second, different symbol for it (the
// pin-type-add list, MapActivity::openPinsAddList()). opticalCenterY is set to
// half the glyph -- nothing here reads it; it exists so this table matches the
// freeink::Icon convention every other icon table in the tree follows.
inline const freeink::Icon* pinGlyphIcon(size_t catalogIndex) {
  static const freeink::Icon icons[kPinSlotCount] = {
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinBaseBits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinParkingBits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinDestBits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinMeetBits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinCampBits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinFavoriteBits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinC1Bits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinC2Bits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinC3Bits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinC4Bits},
      {kPinGlyphPx, kPinGlyphPx, kPinGlyphPx / 2, kPinGlyphPinC5Bits},
  };
  // Same fallback as pinGlyphBits() above: a key this build does not know
  // shows #1's numeral rather than nothing.
  return &icons[catalogIndex < kPinSlotCount ? catalogIndex : 6];
}
