#pragma once

#include <cstdint>

#include "PinCatalog.h"
#include "components/icons/pins_shape.h"

// Which baked bitmap a pin type is drawn with.
//
// One asset per catalogue row, generated by scripts/gen_pin_icons.py from the pin
// shape (src/components/icons/pin-shape.svg) with the row's glyph composited inside
// the head. The device draws two arrays and does no geometry: the shared silhouette
// in white, then the row's outline-plus-glyph in black
// (MapActivity::drawPinBalloon()).
//
// `#1`-`#5` carry their own numeral rather than sharing one glyph -- a 3 is the
// clearest possible way to say "#3", and Lucide has no numerals, so the generator
// bakes those from a font (src/components/icons/pins.icons.txt).
//
// A key this build does not know falls back to `#1`'s numeral. Wrong-but-visible
// beats absent: a pin written by a later firmware must still be findable and
// deletable (PinCatalog.h, the unknown-key rule).
inline const uint8_t* pinShapeBits(size_t catalogIndex) {
  switch (catalogIndex) {
    case 0:
      return kPinShapePinBaseBits;
    case 1:
      return kPinShapePinParkingBits;
    case 2:
      return kPinShapePinDestBits;
    case 3:
      return kPinShapePinMeetBits;
    case 4:
      return kPinShapePinCampBits;
    case 5:
      return kPinShapePinC1Bits;
    case 6:
      return kPinShapePinC2Bits;
    case 7:
      return kPinShapePinC3Bits;
    case 8:
      return kPinShapePinC4Bits;
    case 9:
      return kPinShapePinC5Bits;
    default:
      return kPinShapePinC1Bits;
  }
}
