#pragma once

#include <cstdint>

#include "PinCatalog.h"
#include "components/icons/pins_shape.h"

// Which baked bitmap a pin type is drawn with.
//
// The pin's *shape* is a separate table (kPinShapeFrames, one frame per rotation);
// this is only what goes inside its head. The two are apart on purpose: the shape
// turns so its point can aim at where the pin actually is, and a numeral or a P
// must not turn with it (MapActivity::drawPinBalloon()).
//
// Generated by scripts/gen_pin_icons.py from src/components/icons/pins.icons.txt.
//
// `#1`-`#5` carry their own numeral rather than sharing one glyph -- a 3 is the
// clearest possible way to say "#3", and Lucide has no numerals, so the generator
// bakes those from a font (src/components/icons/pins.icons.txt).
//
// A key this build does not know falls back to `#1`'s numeral. Wrong-but-visible
// beats absent: a pin written by a later firmware must still be findable and
// deletable (PinCatalog.h, the unknown-key rule).
inline const uint8_t* pinGlyphBits(size_t catalogIndex) {
  switch (catalogIndex) {
    case 0:
      return kPinGlyphPinBaseBits;
    case 1:
      return kPinGlyphPinParkingBits;
    case 2:
      return kPinGlyphPinDestBits;
    case 3:
      return kPinGlyphPinMeetBits;
    case 4:
      return kPinGlyphPinCampBits;
    case 5:
      return kPinGlyphPinC1Bits;
    case 6:
      return kPinGlyphPinC2Bits;
    case 7:
      return kPinGlyphPinC3Bits;
    case 8:
      return kPinGlyphPinC4Bits;
    case 9:
      return kPinGlyphPinC5Bits;
    default:
      return kPinGlyphPinC1Bits;
  }
}
